# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'GetIpv6AddressesAddressResult',
]

@pulumi.output_type
class GetIpv6AddressesAddressResult(dict):
    def __init__(__self__, *,
                 actual_interface: str,
                 address: str,
                 advertise: bool,
                 comment: str,
                 disabled: bool,
                 dynamic: bool,
                 eui64: bool,
                 from_pool: str,
                 id: str,
                 interface: str,
                 invalid: bool,
                 link_local: bool,
                 no_dad: bool):
        """
        :param str id: The ID of this resource.
        """
        pulumi.set(__self__, "actual_interface", actual_interface)
        pulumi.set(__self__, "address", address)
        pulumi.set(__self__, "advertise", advertise)
        pulumi.set(__self__, "comment", comment)
        pulumi.set(__self__, "disabled", disabled)
        pulumi.set(__self__, "dynamic", dynamic)
        pulumi.set(__self__, "eui64", eui64)
        pulumi.set(__self__, "from_pool", from_pool)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "interface", interface)
        pulumi.set(__self__, "invalid", invalid)
        pulumi.set(__self__, "link_local", link_local)
        pulumi.set(__self__, "no_dad", no_dad)

    @property
    @pulumi.getter(name="actualInterface")
    def actual_interface(self) -> str:
        return pulumi.get(self, "actual_interface")

    @property
    @pulumi.getter
    def address(self) -> str:
        return pulumi.get(self, "address")

    @property
    @pulumi.getter
    def advertise(self) -> bool:
        return pulumi.get(self, "advertise")

    @property
    @pulumi.getter
    def comment(self) -> str:
        return pulumi.get(self, "comment")

    @property
    @pulumi.getter
    def disabled(self) -> bool:
        return pulumi.get(self, "disabled")

    @property
    @pulumi.getter
    def dynamic(self) -> bool:
        return pulumi.get(self, "dynamic")

    @property
    @pulumi.getter
    def eui64(self) -> bool:
        return pulumi.get(self, "eui64")

    @property
    @pulumi.getter(name="fromPool")
    def from_pool(self) -> str:
        return pulumi.get(self, "from_pool")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The ID of this resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def interface(self) -> str:
        return pulumi.get(self, "interface")

    @property
    @pulumi.getter
    def invalid(self) -> bool:
        return pulumi.get(self, "invalid")

    @property
    @pulumi.getter(name="linkLocal")
    def link_local(self) -> bool:
        return pulumi.get(self, "link_local")

    @property
    @pulumi.getter(name="noDad")
    def no_dad(self) -> bool:
        return pulumi.get(self, "no_dad")


