// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ip

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # Ip.DhcpIpServerLease (Resource)
//
// Creates a DHCP lease on the mikrotik device.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-routeros/sdk/go/routeros/Ip"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := Ip.NewDhcpIpServerLease(ctx, "dhcpLease", &Ip.DhcpIpServerLeaseArgs{
//				Address:    pulumi.String("10.0.0.2"),
//				MacAddress: pulumi.String("AA:BB:CC:DD:11:22"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// #The ID can be found via API or the terminal #The command for the terminal is -> :put [/ip/dhcp-server/lease get [print show-ids]]
//
// ```sh
//
//	$ pulumi import routeros:Ip/dhcpIpServerLease:DhcpIpServerLease dhcp_lease "*0"
//
// ```
type DhcpIpServerLease struct {
	pulumi.CustomResourceState

	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrOutput `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrOutput `pulumi:"___path_"`
	// The IP address of the machine currently holding the DHCP lease.
	ActiveAddress pulumi.StringOutput `pulumi:"activeAddress"`
	// Actual client-id of the client.
	ActiveClientId pulumi.StringOutput `pulumi:"activeClientId"`
	// The hostname of the machine currently holding the DHCP lease.
	ActiveHostname pulumi.StringOutput `pulumi:"activeHostname"`
	// The MAC address of of the machine currently holding the DHCP lease.
	ActiveMacAddress pulumi.StringOutput `pulumi:"activeMacAddress"`
	// Actual dhcp server, which serves this client.
	ActiveServer pulumi.StringOutput `pulumi:"activeServer"`
	// The IP address of the DHCP lease to be created.
	Address pulumi.StringOutput `pulumi:"address"`
	// Address list to which address will be added if lease is bound.
	AddressLists pulumi.StringPtrOutput `pulumi:"addressLists"`
	// Circuit ID of DHCP relay agent. If each character should be valid ASCII text symbol or else this value is displayed as hex dump.
	AgentCircuitId pulumi.StringOutput `pulumi:"agentCircuitId"`
	// Remote ID, set by DHCP relay agent.
	AgentRemoteId pulumi.StringOutput `pulumi:"agentRemoteId"`
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	AllowDualStackQueue pulumi.BoolPtrOutput `pulumi:"allowDualStackQueue"`
	// Send all replies as broadcasts.
	AlwaysBroadcast pulumi.BoolPtrOutput `pulumi:"alwaysBroadcast"`
	// Whether to block access for this DHCP client (true|false).
	BlockAccess pulumi.BoolPtrOutput `pulumi:"blockAccess"`
	// Whether the lease is blocked.
	Blocked pulumi.BoolOutput `pulumi:"blocked"`
	// If specified, must match DHCP 'client identifier' option of the request.
	ClientId pulumi.StringPtrOutput `pulumi:"clientId"`
	Comment  pulumi.StringPtrOutput `pulumi:"comment"`
	// Add additional DHCP options.
	DhcpOption pulumi.StringPtrOutput `pulumi:"dhcpOption"`
	// Add additional set of DHCP options.
	DhcpOptionSet pulumi.StringPtrOutput `pulumi:"dhcpOptionSet"`
	Disabled      pulumi.BoolPtrOutput   `pulumi:"disabled"`
	// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device. Defaults to false.
	Dynamic pulumi.BoolPtrOutput `pulumi:"dynamic"`
	// Time until lease expires.
	ExpiresAfter pulumi.StringOutput `pulumi:"expiresAfter"`
	// The hostname of the device
	HostName pulumi.StringOutput `pulumi:"hostName"`
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	InsertQueueBefore pulumi.StringPtrOutput `pulumi:"insertQueueBefore"`
	LastSeen          pulumi.StringOutput    `pulumi:"lastSeen"`
	// Time that the client may use the address. If set to 0s lease will never expire.
	LeaseTime pulumi.StringPtrOutput `pulumi:"leaseTime"`
	// The MAC addreess of the DHCP lease to be created.
	MacAddress pulumi.StringOutput `pulumi:"macAddress"`
	// Shows if this dynamic lease is authenticated by RADIUS or not.
	Radius pulumi.StringOutput `pulumi:"radius"`
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	RateLimit pulumi.StringPtrOutput `pulumi:"rateLimit"`
	// Server name which serves this client.
	Server pulumi.StringPtrOutput `pulumi:"server"`
	// Source MAC address.
	SrcMacAddress pulumi.StringOutput `pulumi:"srcMacAddress"`
	// Lease status.
	Status pulumi.StringOutput `pulumi:"status"`
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	UseSrcMac pulumi.BoolPtrOutput `pulumi:"useSrcMac"`
}

// NewDhcpIpServerLease registers a new resource with the given unique name, arguments, and options.
func NewDhcpIpServerLease(ctx *pulumi.Context,
	name string, args *DhcpIpServerLeaseArgs, opts ...pulumi.ResourceOption) (*DhcpIpServerLease, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Address == nil {
		return nil, errors.New("invalid value for required argument 'Address'")
	}
	if args.MacAddress == nil {
		return nil, errors.New("invalid value for required argument 'MacAddress'")
	}
	var resource DhcpIpServerLease
	err := ctx.RegisterResource("routeros:Ip/dhcpIpServerLease:DhcpIpServerLease", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDhcpIpServerLease gets an existing DhcpIpServerLease resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDhcpIpServerLease(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DhcpIpServerLeaseState, opts ...pulumi.ResourceOption) (*DhcpIpServerLease, error) {
	var resource DhcpIpServerLease
	err := ctx.ReadResource("routeros:Ip/dhcpIpServerLease:DhcpIpServerLease", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DhcpIpServerLease resources.
type dhcpIpServerLeaseState struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ *int `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ *string `pulumi:"___path_"`
	// The IP address of the machine currently holding the DHCP lease.
	ActiveAddress *string `pulumi:"activeAddress"`
	// Actual client-id of the client.
	ActiveClientId *string `pulumi:"activeClientId"`
	// The hostname of the machine currently holding the DHCP lease.
	ActiveHostname *string `pulumi:"activeHostname"`
	// The MAC address of of the machine currently holding the DHCP lease.
	ActiveMacAddress *string `pulumi:"activeMacAddress"`
	// Actual dhcp server, which serves this client.
	ActiveServer *string `pulumi:"activeServer"`
	// The IP address of the DHCP lease to be created.
	Address *string `pulumi:"address"`
	// Address list to which address will be added if lease is bound.
	AddressLists *string `pulumi:"addressLists"`
	// Circuit ID of DHCP relay agent. If each character should be valid ASCII text symbol or else this value is displayed as hex dump.
	AgentCircuitId *string `pulumi:"agentCircuitId"`
	// Remote ID, set by DHCP relay agent.
	AgentRemoteId *string `pulumi:"agentRemoteId"`
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	AllowDualStackQueue *bool `pulumi:"allowDualStackQueue"`
	// Send all replies as broadcasts.
	AlwaysBroadcast *bool `pulumi:"alwaysBroadcast"`
	// Whether to block access for this DHCP client (true|false).
	BlockAccess *bool `pulumi:"blockAccess"`
	// Whether the lease is blocked.
	Blocked *bool `pulumi:"blocked"`
	// If specified, must match DHCP 'client identifier' option of the request.
	ClientId *string `pulumi:"clientId"`
	Comment  *string `pulumi:"comment"`
	// Add additional DHCP options.
	DhcpOption *string `pulumi:"dhcpOption"`
	// Add additional set of DHCP options.
	DhcpOptionSet *string `pulumi:"dhcpOptionSet"`
	Disabled      *bool   `pulumi:"disabled"`
	// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device. Defaults to false.
	Dynamic *bool `pulumi:"dynamic"`
	// Time until lease expires.
	ExpiresAfter *string `pulumi:"expiresAfter"`
	// The hostname of the device
	HostName *string `pulumi:"hostName"`
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	InsertQueueBefore *string `pulumi:"insertQueueBefore"`
	LastSeen          *string `pulumi:"lastSeen"`
	// Time that the client may use the address. If set to 0s lease will never expire.
	LeaseTime *string `pulumi:"leaseTime"`
	// The MAC addreess of the DHCP lease to be created.
	MacAddress *string `pulumi:"macAddress"`
	// Shows if this dynamic lease is authenticated by RADIUS or not.
	Radius *string `pulumi:"radius"`
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	RateLimit *string `pulumi:"rateLimit"`
	// Server name which serves this client.
	Server *string `pulumi:"server"`
	// Source MAC address.
	SrcMacAddress *string `pulumi:"srcMacAddress"`
	// Lease status.
	Status *string `pulumi:"status"`
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	UseSrcMac *bool `pulumi:"useSrcMac"`
}

type DhcpIpServerLeaseState struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrInput
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrInput
	// The IP address of the machine currently holding the DHCP lease.
	ActiveAddress pulumi.StringPtrInput
	// Actual client-id of the client.
	ActiveClientId pulumi.StringPtrInput
	// The hostname of the machine currently holding the DHCP lease.
	ActiveHostname pulumi.StringPtrInput
	// The MAC address of of the machine currently holding the DHCP lease.
	ActiveMacAddress pulumi.StringPtrInput
	// Actual dhcp server, which serves this client.
	ActiveServer pulumi.StringPtrInput
	// The IP address of the DHCP lease to be created.
	Address pulumi.StringPtrInput
	// Address list to which address will be added if lease is bound.
	AddressLists pulumi.StringPtrInput
	// Circuit ID of DHCP relay agent. If each character should be valid ASCII text symbol or else this value is displayed as hex dump.
	AgentCircuitId pulumi.StringPtrInput
	// Remote ID, set by DHCP relay agent.
	AgentRemoteId pulumi.StringPtrInput
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	AllowDualStackQueue pulumi.BoolPtrInput
	// Send all replies as broadcasts.
	AlwaysBroadcast pulumi.BoolPtrInput
	// Whether to block access for this DHCP client (true|false).
	BlockAccess pulumi.BoolPtrInput
	// Whether the lease is blocked.
	Blocked pulumi.BoolPtrInput
	// If specified, must match DHCP 'client identifier' option of the request.
	ClientId pulumi.StringPtrInput
	Comment  pulumi.StringPtrInput
	// Add additional DHCP options.
	DhcpOption pulumi.StringPtrInput
	// Add additional set of DHCP options.
	DhcpOptionSet pulumi.StringPtrInput
	Disabled      pulumi.BoolPtrInput
	// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device. Defaults to false.
	Dynamic pulumi.BoolPtrInput
	// Time until lease expires.
	ExpiresAfter pulumi.StringPtrInput
	// The hostname of the device
	HostName pulumi.StringPtrInput
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	InsertQueueBefore pulumi.StringPtrInput
	LastSeen          pulumi.StringPtrInput
	// Time that the client may use the address. If set to 0s lease will never expire.
	LeaseTime pulumi.StringPtrInput
	// The MAC addreess of the DHCP lease to be created.
	MacAddress pulumi.StringPtrInput
	// Shows if this dynamic lease is authenticated by RADIUS or not.
	Radius pulumi.StringPtrInput
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	RateLimit pulumi.StringPtrInput
	// Server name which serves this client.
	Server pulumi.StringPtrInput
	// Source MAC address.
	SrcMacAddress pulumi.StringPtrInput
	// Lease status.
	Status pulumi.StringPtrInput
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	UseSrcMac pulumi.BoolPtrInput
}

func (DhcpIpServerLeaseState) ElementType() reflect.Type {
	return reflect.TypeOf((*dhcpIpServerLeaseState)(nil)).Elem()
}

type dhcpIpServerLeaseArgs struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ *int `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ *string `pulumi:"___path_"`
	// The IP address of the DHCP lease to be created.
	Address string `pulumi:"address"`
	// Address list to which address will be added if lease is bound.
	AddressLists *string `pulumi:"addressLists"`
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	AllowDualStackQueue *bool `pulumi:"allowDualStackQueue"`
	// Send all replies as broadcasts.
	AlwaysBroadcast *bool `pulumi:"alwaysBroadcast"`
	// Whether to block access for this DHCP client (true|false).
	BlockAccess *bool `pulumi:"blockAccess"`
	// If specified, must match DHCP 'client identifier' option of the request.
	ClientId *string `pulumi:"clientId"`
	Comment  *string `pulumi:"comment"`
	// Add additional DHCP options.
	DhcpOption *string `pulumi:"dhcpOption"`
	// Add additional set of DHCP options.
	DhcpOptionSet *string `pulumi:"dhcpOptionSet"`
	Disabled      *bool   `pulumi:"disabled"`
	// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device. Defaults to false.
	Dynamic *bool `pulumi:"dynamic"`
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	InsertQueueBefore *string `pulumi:"insertQueueBefore"`
	// Time that the client may use the address. If set to 0s lease will never expire.
	LeaseTime *string `pulumi:"leaseTime"`
	// The MAC addreess of the DHCP lease to be created.
	MacAddress string `pulumi:"macAddress"`
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	RateLimit *string `pulumi:"rateLimit"`
	// Server name which serves this client.
	Server *string `pulumi:"server"`
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	UseSrcMac *bool `pulumi:"useSrcMac"`
}

// The set of arguments for constructing a DhcpIpServerLease resource.
type DhcpIpServerLeaseArgs struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrInput
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrInput
	// The IP address of the DHCP lease to be created.
	Address pulumi.StringInput
	// Address list to which address will be added if lease is bound.
	AddressLists pulumi.StringPtrInput
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	AllowDualStackQueue pulumi.BoolPtrInput
	// Send all replies as broadcasts.
	AlwaysBroadcast pulumi.BoolPtrInput
	// Whether to block access for this DHCP client (true|false).
	BlockAccess pulumi.BoolPtrInput
	// If specified, must match DHCP 'client identifier' option of the request.
	ClientId pulumi.StringPtrInput
	Comment  pulumi.StringPtrInput
	// Add additional DHCP options.
	DhcpOption pulumi.StringPtrInput
	// Add additional set of DHCP options.
	DhcpOptionSet pulumi.StringPtrInput
	Disabled      pulumi.BoolPtrInput
	// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device. Defaults to false.
	Dynamic pulumi.BoolPtrInput
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	InsertQueueBefore pulumi.StringPtrInput
	// Time that the client may use the address. If set to 0s lease will never expire.
	LeaseTime pulumi.StringPtrInput
	// The MAC addreess of the DHCP lease to be created.
	MacAddress pulumi.StringInput
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	RateLimit pulumi.StringPtrInput
	// Server name which serves this client.
	Server pulumi.StringPtrInput
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	UseSrcMac pulumi.BoolPtrInput
}

func (DhcpIpServerLeaseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dhcpIpServerLeaseArgs)(nil)).Elem()
}

type DhcpIpServerLeaseInput interface {
	pulumi.Input

	ToDhcpIpServerLeaseOutput() DhcpIpServerLeaseOutput
	ToDhcpIpServerLeaseOutputWithContext(ctx context.Context) DhcpIpServerLeaseOutput
}

func (*DhcpIpServerLease) ElementType() reflect.Type {
	return reflect.TypeOf((**DhcpIpServerLease)(nil)).Elem()
}

func (i *DhcpIpServerLease) ToDhcpIpServerLeaseOutput() DhcpIpServerLeaseOutput {
	return i.ToDhcpIpServerLeaseOutputWithContext(context.Background())
}

func (i *DhcpIpServerLease) ToDhcpIpServerLeaseOutputWithContext(ctx context.Context) DhcpIpServerLeaseOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DhcpIpServerLeaseOutput)
}

// DhcpIpServerLeaseArrayInput is an input type that accepts DhcpIpServerLeaseArray and DhcpIpServerLeaseArrayOutput values.
// You can construct a concrete instance of `DhcpIpServerLeaseArrayInput` via:
//
//	DhcpIpServerLeaseArray{ DhcpIpServerLeaseArgs{...} }
type DhcpIpServerLeaseArrayInput interface {
	pulumi.Input

	ToDhcpIpServerLeaseArrayOutput() DhcpIpServerLeaseArrayOutput
	ToDhcpIpServerLeaseArrayOutputWithContext(context.Context) DhcpIpServerLeaseArrayOutput
}

type DhcpIpServerLeaseArray []DhcpIpServerLeaseInput

func (DhcpIpServerLeaseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DhcpIpServerLease)(nil)).Elem()
}

func (i DhcpIpServerLeaseArray) ToDhcpIpServerLeaseArrayOutput() DhcpIpServerLeaseArrayOutput {
	return i.ToDhcpIpServerLeaseArrayOutputWithContext(context.Background())
}

func (i DhcpIpServerLeaseArray) ToDhcpIpServerLeaseArrayOutputWithContext(ctx context.Context) DhcpIpServerLeaseArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DhcpIpServerLeaseArrayOutput)
}

// DhcpIpServerLeaseMapInput is an input type that accepts DhcpIpServerLeaseMap and DhcpIpServerLeaseMapOutput values.
// You can construct a concrete instance of `DhcpIpServerLeaseMapInput` via:
//
//	DhcpIpServerLeaseMap{ "key": DhcpIpServerLeaseArgs{...} }
type DhcpIpServerLeaseMapInput interface {
	pulumi.Input

	ToDhcpIpServerLeaseMapOutput() DhcpIpServerLeaseMapOutput
	ToDhcpIpServerLeaseMapOutputWithContext(context.Context) DhcpIpServerLeaseMapOutput
}

type DhcpIpServerLeaseMap map[string]DhcpIpServerLeaseInput

func (DhcpIpServerLeaseMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DhcpIpServerLease)(nil)).Elem()
}

func (i DhcpIpServerLeaseMap) ToDhcpIpServerLeaseMapOutput() DhcpIpServerLeaseMapOutput {
	return i.ToDhcpIpServerLeaseMapOutputWithContext(context.Background())
}

func (i DhcpIpServerLeaseMap) ToDhcpIpServerLeaseMapOutputWithContext(ctx context.Context) DhcpIpServerLeaseMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DhcpIpServerLeaseMapOutput)
}

type DhcpIpServerLeaseOutput struct{ *pulumi.OutputState }

func (DhcpIpServerLeaseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DhcpIpServerLease)(nil)).Elem()
}

func (o DhcpIpServerLeaseOutput) ToDhcpIpServerLeaseOutput() DhcpIpServerLeaseOutput {
	return o
}

func (o DhcpIpServerLeaseOutput) ToDhcpIpServerLeaseOutputWithContext(ctx context.Context) DhcpIpServerLeaseOutput {
	return o
}

// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
func (o DhcpIpServerLeaseOutput) ___id_() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.IntPtrOutput { return v.___id_ }).(pulumi.IntPtrOutput)
}

// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
func (o DhcpIpServerLeaseOutput) ___path_() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringPtrOutput { return v.___path_ }).(pulumi.StringPtrOutput)
}

// The IP address of the machine currently holding the DHCP lease.
func (o DhcpIpServerLeaseOutput) ActiveAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.ActiveAddress }).(pulumi.StringOutput)
}

// Actual client-id of the client.
func (o DhcpIpServerLeaseOutput) ActiveClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.ActiveClientId }).(pulumi.StringOutput)
}

// The hostname of the machine currently holding the DHCP lease.
func (o DhcpIpServerLeaseOutput) ActiveHostname() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.ActiveHostname }).(pulumi.StringOutput)
}

// The MAC address of of the machine currently holding the DHCP lease.
func (o DhcpIpServerLeaseOutput) ActiveMacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.ActiveMacAddress }).(pulumi.StringOutput)
}

// Actual dhcp server, which serves this client.
func (o DhcpIpServerLeaseOutput) ActiveServer() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.ActiveServer }).(pulumi.StringOutput)
}

// The IP address of the DHCP lease to be created.
func (o DhcpIpServerLeaseOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.Address }).(pulumi.StringOutput)
}

// Address list to which address will be added if lease is bound.
func (o DhcpIpServerLeaseOutput) AddressLists() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringPtrOutput { return v.AddressLists }).(pulumi.StringPtrOutput)
}

// Circuit ID of DHCP relay agent. If each character should be valid ASCII text symbol or else this value is displayed as hex dump.
func (o DhcpIpServerLeaseOutput) AgentCircuitId() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.AgentCircuitId }).(pulumi.StringOutput)
}

// Remote ID, set by DHCP relay agent.
func (o DhcpIpServerLeaseOutput) AgentRemoteId() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.AgentRemoteId }).(pulumi.StringOutput)
}

// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
func (o DhcpIpServerLeaseOutput) AllowDualStackQueue() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.BoolPtrOutput { return v.AllowDualStackQueue }).(pulumi.BoolPtrOutput)
}

// Send all replies as broadcasts.
func (o DhcpIpServerLeaseOutput) AlwaysBroadcast() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.BoolPtrOutput { return v.AlwaysBroadcast }).(pulumi.BoolPtrOutput)
}

// Whether to block access for this DHCP client (true|false).
func (o DhcpIpServerLeaseOutput) BlockAccess() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.BoolPtrOutput { return v.BlockAccess }).(pulumi.BoolPtrOutput)
}

// Whether the lease is blocked.
func (o DhcpIpServerLeaseOutput) Blocked() pulumi.BoolOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.BoolOutput { return v.Blocked }).(pulumi.BoolOutput)
}

// If specified, must match DHCP 'client identifier' option of the request.
func (o DhcpIpServerLeaseOutput) ClientId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringPtrOutput { return v.ClientId }).(pulumi.StringPtrOutput)
}

func (o DhcpIpServerLeaseOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// Add additional DHCP options.
func (o DhcpIpServerLeaseOutput) DhcpOption() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringPtrOutput { return v.DhcpOption }).(pulumi.StringPtrOutput)
}

// Add additional set of DHCP options.
func (o DhcpIpServerLeaseOutput) DhcpOptionSet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringPtrOutput { return v.DhcpOptionSet }).(pulumi.StringPtrOutput)
}

func (o DhcpIpServerLeaseOutput) Disabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.BoolPtrOutput { return v.Disabled }).(pulumi.BoolPtrOutput)
}

// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device. Defaults to false.
func (o DhcpIpServerLeaseOutput) Dynamic() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.BoolPtrOutput { return v.Dynamic }).(pulumi.BoolPtrOutput)
}

// Time until lease expires.
func (o DhcpIpServerLeaseOutput) ExpiresAfter() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.ExpiresAfter }).(pulumi.StringOutput)
}

// The hostname of the device
func (o DhcpIpServerLeaseOutput) HostName() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.HostName }).(pulumi.StringOutput)
}

// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
func (o DhcpIpServerLeaseOutput) InsertQueueBefore() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringPtrOutput { return v.InsertQueueBefore }).(pulumi.StringPtrOutput)
}

func (o DhcpIpServerLeaseOutput) LastSeen() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.LastSeen }).(pulumi.StringOutput)
}

// Time that the client may use the address. If set to 0s lease will never expire.
func (o DhcpIpServerLeaseOutput) LeaseTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringPtrOutput { return v.LeaseTime }).(pulumi.StringPtrOutput)
}

// The MAC addreess of the DHCP lease to be created.
func (o DhcpIpServerLeaseOutput) MacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.MacAddress }).(pulumi.StringOutput)
}

// Shows if this dynamic lease is authenticated by RADIUS or not.
func (o DhcpIpServerLeaseOutput) Radius() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.Radius }).(pulumi.StringOutput)
}

// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
func (o DhcpIpServerLeaseOutput) RateLimit() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringPtrOutput { return v.RateLimit }).(pulumi.StringPtrOutput)
}

// Server name which serves this client.
func (o DhcpIpServerLeaseOutput) Server() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringPtrOutput { return v.Server }).(pulumi.StringPtrOutput)
}

// Source MAC address.
func (o DhcpIpServerLeaseOutput) SrcMacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.SrcMacAddress }).(pulumi.StringOutput)
}

// Lease status.
func (o DhcpIpServerLeaseOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// When this option is set server uses source MAC address instead of received CHADDR to assign address.
func (o DhcpIpServerLeaseOutput) UseSrcMac() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DhcpIpServerLease) pulumi.BoolPtrOutput { return v.UseSrcMac }).(pulumi.BoolPtrOutput)
}

type DhcpIpServerLeaseArrayOutput struct{ *pulumi.OutputState }

func (DhcpIpServerLeaseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DhcpIpServerLease)(nil)).Elem()
}

func (o DhcpIpServerLeaseArrayOutput) ToDhcpIpServerLeaseArrayOutput() DhcpIpServerLeaseArrayOutput {
	return o
}

func (o DhcpIpServerLeaseArrayOutput) ToDhcpIpServerLeaseArrayOutputWithContext(ctx context.Context) DhcpIpServerLeaseArrayOutput {
	return o
}

func (o DhcpIpServerLeaseArrayOutput) Index(i pulumi.IntInput) DhcpIpServerLeaseOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DhcpIpServerLease {
		return vs[0].([]*DhcpIpServerLease)[vs[1].(int)]
	}).(DhcpIpServerLeaseOutput)
}

type DhcpIpServerLeaseMapOutput struct{ *pulumi.OutputState }

func (DhcpIpServerLeaseMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DhcpIpServerLease)(nil)).Elem()
}

func (o DhcpIpServerLeaseMapOutput) ToDhcpIpServerLeaseMapOutput() DhcpIpServerLeaseMapOutput {
	return o
}

func (o DhcpIpServerLeaseMapOutput) ToDhcpIpServerLeaseMapOutputWithContext(ctx context.Context) DhcpIpServerLeaseMapOutput {
	return o
}

func (o DhcpIpServerLeaseMapOutput) MapIndex(k pulumi.StringInput) DhcpIpServerLeaseOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DhcpIpServerLease {
		return vs[0].(map[string]*DhcpIpServerLease)[vs[1].(string)]
	}).(DhcpIpServerLeaseOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DhcpIpServerLeaseInput)(nil)).Elem(), &DhcpIpServerLease{})
	pulumi.RegisterInputType(reflect.TypeOf((*DhcpIpServerLeaseArrayInput)(nil)).Elem(), DhcpIpServerLeaseArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DhcpIpServerLeaseMapInput)(nil)).Elem(), DhcpIpServerLeaseMap{})
	pulumi.RegisterOutputType(DhcpIpServerLeaseOutput{})
	pulumi.RegisterOutputType(DhcpIpServerLeaseArrayOutput{})
	pulumi.RegisterOutputType(DhcpIpServerLeaseMapOutput{})
}
