// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ipv6

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetIpv6Addresses(ctx *pulumi.Context, args *GetIpv6AddressesArgs, opts ...pulumi.InvokeOption) (*GetIpv6AddressesResult, error) {
	var rv GetIpv6AddressesResult
	err := ctx.Invoke("routeros:Ipv6/getIpv6Addresses:getIpv6Addresses", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIpv6Addresses.
type GetIpv6AddressesArgs struct {
	___id_   *int    `pulumi:"___id_"`
	___path_ *string `pulumi:"___path_"`
	// Additional request filtering options.
	Filter map[string]interface{} `pulumi:"filter"`
}

// A collection of values returned by getIpv6Addresses.
type GetIpv6AddressesResult struct {
	___id_    *int                      `pulumi:"___id_"`
	___path_  *string                   `pulumi:"___path_"`
	Addresses []GetIpv6AddressesAddress `pulumi:"addresses"`
	// Additional request filtering options.
	Filter map[string]interface{} `pulumi:"filter"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}

func GetIpv6AddressesOutput(ctx *pulumi.Context, args GetIpv6AddressesOutputArgs, opts ...pulumi.InvokeOption) GetIpv6AddressesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetIpv6AddressesResult, error) {
			args := v.(GetIpv6AddressesArgs)
			r, err := GetIpv6Addresses(ctx, &args, opts...)
			var s GetIpv6AddressesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetIpv6AddressesResultOutput)
}

// A collection of arguments for invoking getIpv6Addresses.
type GetIpv6AddressesOutputArgs struct {
	___id_   pulumi.IntPtrInput    `pulumi:"___id_"`
	___path_ pulumi.StringPtrInput `pulumi:"___path_"`
	// Additional request filtering options.
	Filter pulumi.MapInput `pulumi:"filter"`
}

func (GetIpv6AddressesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIpv6AddressesArgs)(nil)).Elem()
}

// A collection of values returned by getIpv6Addresses.
type GetIpv6AddressesResultOutput struct{ *pulumi.OutputState }

func (GetIpv6AddressesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIpv6AddressesResult)(nil)).Elem()
}

func (o GetIpv6AddressesResultOutput) ToGetIpv6AddressesResultOutput() GetIpv6AddressesResultOutput {
	return o
}

func (o GetIpv6AddressesResultOutput) ToGetIpv6AddressesResultOutputWithContext(ctx context.Context) GetIpv6AddressesResultOutput {
	return o
}

func (o GetIpv6AddressesResultOutput) ___id_() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetIpv6AddressesResult) *int { return v.___id_ }).(pulumi.IntPtrOutput)
}

func (o GetIpv6AddressesResultOutput) ___path_() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetIpv6AddressesResult) *string { return v.___path_ }).(pulumi.StringPtrOutput)
}

func (o GetIpv6AddressesResultOutput) Addresses() GetIpv6AddressesAddressArrayOutput {
	return o.ApplyT(func(v GetIpv6AddressesResult) []GetIpv6AddressesAddress { return v.Addresses }).(GetIpv6AddressesAddressArrayOutput)
}

// Additional request filtering options.
func (o GetIpv6AddressesResultOutput) Filter() pulumi.MapOutput {
	return o.ApplyT(func(v GetIpv6AddressesResult) map[string]interface{} { return v.Filter }).(pulumi.MapOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetIpv6AddressesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetIpv6AddressesResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetIpv6AddressesResultOutput{})
}
