// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package routeros

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # ResourceOpenVPNServer (Resource)
//
// ##### *<span style="color:red">This resource requires a minimum version of RouterOS 7.8!</span>*
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-routeros/sdk/go/routeros"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := routeros.NewResourceIPPool(ctx, "ovpn-pool", &routeros.ResourceIPPoolArgs{
//				Ranges: pulumi.StringArray{
//					pulumi.String("192.168.77.2-192.168.77.254"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			ovpnCa, err := routeros.NewResourceSystemCertificate(ctx, "ovpnCa", &routeros.ResourceSystemCertificateArgs{
//				CommonName: pulumi.String("OpenVPN Root CA"),
//				KeySize:    pulumi.String("prime256v1"),
//				KeyUsages: pulumi.StringArray{
//					pulumi.String("key-cert-sign"),
//					pulumi.String("crl-sign"),
//				},
//				Trusted: pulumi.Bool(true),
//				Signs: routeros.ResourceSystemCertificateSignArray{
//					nil,
//				},
//			})
//			if err != nil {
//				return err
//			}
//			ovpnServerCrt, err := routeros.NewResourceSystemCertificate(ctx, "ovpnServerCrt", &routeros.ResourceSystemCertificateArgs{
//				CommonName: pulumi.String("Mikrotik OpenVPN"),
//				KeySize:    pulumi.String("prime256v1"),
//				KeyUsages: pulumi.StringArray{
//					pulumi.String("digital-signature"),
//					pulumi.String("key-encipherment"),
//					pulumi.String("tls-server"),
//				},
//				Signs: routeros.ResourceSystemCertificateSignArray{
//					&routeros.ResourceSystemCertificateSignArgs{
//						Ca: ovpnCa.Name,
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			testResourcePPPProfile, err := routeros.NewResourcePPPProfile(ctx, "testResourcePPPProfile", &routeros.ResourcePPPProfileArgs{
//				LocalAddress:  pulumi.String("192.168.77.1"),
//				RemoteAddress: pulumi.String("ovpn-pool"),
//				UseUpnp:       pulumi.String("no"),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = routeros.NewResourcePPPSecret(ctx, "testResourcePPPSecret", &routeros.ResourcePPPSecretArgs{
//				Password: pulumi.String("123"),
//				Profile:  testResourcePPPProfile.Name,
//			})
//			if err != nil {
//				return err
//			}
//			server, err := routeros.NewResourceOpenVPNServer(ctx, "server", &routeros.ResourceOpenVPNServerArgs{
//				Enabled:        pulumi.Bool(true),
//				Certificate:    ovpnServerCrt.Name,
//				Auth:           pulumi.String("sha256,sha512"),
//				TlsVersion:     pulumi.String("only-1.2"),
//				DefaultProfile: testResourcePPPProfile.Name,
//			})
//			if err != nil {
//				return err
//			}
//			_, err = routeros.NewResourceInterfaceOpenVPNServer(ctx, "user1", &routeros.ResourceInterfaceOpenVPNServerArgs{
//				User: pulumi.String("user1"),
//			}, pulumi.DependsOn([]pulumi.Resource{
//				server,
//			}))
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
//
//	$ pulumi import routeros:index/resourceOpenVPNServer:ResourceOpenVPNServer server .
//
// ```
type ResourceOpenVPNServer struct {
	pulumi.CustomResourceState

	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrOutput `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrOutput `pulumi:"___path_"`
	// Authentication methods that the server will accept.
	Auth pulumi.StringPtrOutput `pulumi:"auth"`
	// Name of the certificate that the OVPN server will use.
	Certificate pulumi.StringOutput `pulumi:"certificate"`
	// Allowed ciphers.
	Cipher pulumi.StringPtrOutput `pulumi:"cipher"`
	// Default profile to use.
	DefaultProfile pulumi.StringPtrOutput `pulumi:"defaultProfile"`
	// Specifies if IPv6 IP tunneling mode should be possible with this OVPN server.
	EnableTunIpv6 pulumi.BoolPtrOutput `pulumi:"enableTunIpv6"`
	// Defines whether the OVPN server is enabled or not.
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// Length of IPv6 prefix for IPv6 address which will be used when generating OVPN interface on the server side.
	Ipv6PrefixLen pulumi.IntPtrOutput `pulumi:"ipv6PrefixLen"`
	// Defines  the time period (in seconds) after which the router is starting to send  keepalive packets every second. If no traffic and no keepalive  responses have come for that period of time (i.e. 2 *  keepalive-timeout), not responding client is proclaimed disconnected
	KeepaliveTimeout pulumi.StringPtrOutput `pulumi:"keepaliveTimeout"`
	// Automatically generated MAC address of the server.
	MacAddress pulumi.StringOutput `pulumi:"macAddress"`
	// Maximum Transmission Unit. Max packet size that the OVPN interface will be able to send without packet fragmentation.
	MaxMtu pulumi.IntPtrOutput `pulumi:"maxMtu"`
	// Layer3 or layer2 tunnel mode (alternatively tun, tap)
	Mode pulumi.StringPtrOutput `pulumi:"mode"`
	// Subnet mask to be applied to the client.
	Netmask pulumi.IntPtrOutput `pulumi:"netmask"`
	// Port to run the server on.
	Port pulumi.IntPtrOutput `pulumi:"port"`
	// indicates the protocol to use when connecting with the remote endpoint.
	Protocol pulumi.StringPtrOutput `pulumi:"protocol"`
	// Specifies what kind of routes the OVPN client must add to the routing table. def1 – Use this flag to override the default gateway by using 0.0.0.0/1 and  128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of overriding  but not wiping out the original default gateway. disabled - Do not send redirect-gateway flags to the OVPN client. ipv6 - Redirect IPv6 routing into the tunnel on the client side. This works  similarly to the def1 flag, that is, more specific IPv6 routes are added  (2000::/4 and 3000::/4), covering the whole IPv6 unicast space.
	RedirectGateway pulumi.StringPtrOutput `pulumi:"redirectGateway"`
	// Renegotiate data channel key after n seconds (default=3600).
	RenegSec pulumi.IntPtrOutput `pulumi:"renegSec"`
	// If set to yes, then the server checks whether the client's certificate belongs to the same certificate chain.
	RequireClientCertificate pulumi.BoolPtrOutput `pulumi:"requireClientCertificate"`
	// Specifies which TLS versions to allow.
	TlsVersion pulumi.StringPtrOutput `pulumi:"tlsVersion"`
	// IPv6 prefix address which will be used when generating the OVPN interface on the server side.
	TunServerIpv6 pulumi.StringPtrOutput `pulumi:"tunServerIpv6"`
}

// NewResourceOpenVPNServer registers a new resource with the given unique name, arguments, and options.
func NewResourceOpenVPNServer(ctx *pulumi.Context,
	name string, args *ResourceOpenVPNServerArgs, opts ...pulumi.ResourceOption) (*ResourceOpenVPNServer, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Certificate == nil {
		return nil, errors.New("invalid value for required argument 'Certificate'")
	}
	var resource ResourceOpenVPNServer
	err := ctx.RegisterResource("routeros:index/resourceOpenVPNServer:ResourceOpenVPNServer", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetResourceOpenVPNServer gets an existing ResourceOpenVPNServer resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetResourceOpenVPNServer(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ResourceOpenVPNServerState, opts ...pulumi.ResourceOption) (*ResourceOpenVPNServer, error) {
	var resource ResourceOpenVPNServer
	err := ctx.ReadResource("routeros:index/resourceOpenVPNServer:ResourceOpenVPNServer", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ResourceOpenVPNServer resources.
type resourceOpenVPNServerState struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ *int `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ *string `pulumi:"___path_"`
	// Authentication methods that the server will accept.
	Auth *string `pulumi:"auth"`
	// Name of the certificate that the OVPN server will use.
	Certificate *string `pulumi:"certificate"`
	// Allowed ciphers.
	Cipher *string `pulumi:"cipher"`
	// Default profile to use.
	DefaultProfile *string `pulumi:"defaultProfile"`
	// Specifies if IPv6 IP tunneling mode should be possible with this OVPN server.
	EnableTunIpv6 *bool `pulumi:"enableTunIpv6"`
	// Defines whether the OVPN server is enabled or not.
	Enabled *bool `pulumi:"enabled"`
	// Length of IPv6 prefix for IPv6 address which will be used when generating OVPN interface on the server side.
	Ipv6PrefixLen *int `pulumi:"ipv6PrefixLen"`
	// Defines  the time period (in seconds) after which the router is starting to send  keepalive packets every second. If no traffic and no keepalive  responses have come for that period of time (i.e. 2 *  keepalive-timeout), not responding client is proclaimed disconnected
	KeepaliveTimeout *string `pulumi:"keepaliveTimeout"`
	// Automatically generated MAC address of the server.
	MacAddress *string `pulumi:"macAddress"`
	// Maximum Transmission Unit. Max packet size that the OVPN interface will be able to send without packet fragmentation.
	MaxMtu *int `pulumi:"maxMtu"`
	// Layer3 or layer2 tunnel mode (alternatively tun, tap)
	Mode *string `pulumi:"mode"`
	// Subnet mask to be applied to the client.
	Netmask *int `pulumi:"netmask"`
	// Port to run the server on.
	Port *int `pulumi:"port"`
	// indicates the protocol to use when connecting with the remote endpoint.
	Protocol *string `pulumi:"protocol"`
	// Specifies what kind of routes the OVPN client must add to the routing table. def1 – Use this flag to override the default gateway by using 0.0.0.0/1 and  128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of overriding  but not wiping out the original default gateway. disabled - Do not send redirect-gateway flags to the OVPN client. ipv6 - Redirect IPv6 routing into the tunnel on the client side. This works  similarly to the def1 flag, that is, more specific IPv6 routes are added  (2000::/4 and 3000::/4), covering the whole IPv6 unicast space.
	RedirectGateway *string `pulumi:"redirectGateway"`
	// Renegotiate data channel key after n seconds (default=3600).
	RenegSec *int `pulumi:"renegSec"`
	// If set to yes, then the server checks whether the client's certificate belongs to the same certificate chain.
	RequireClientCertificate *bool `pulumi:"requireClientCertificate"`
	// Specifies which TLS versions to allow.
	TlsVersion *string `pulumi:"tlsVersion"`
	// IPv6 prefix address which will be used when generating the OVPN interface on the server side.
	TunServerIpv6 *string `pulumi:"tunServerIpv6"`
}

type ResourceOpenVPNServerState struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrInput
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrInput
	// Authentication methods that the server will accept.
	Auth pulumi.StringPtrInput
	// Name of the certificate that the OVPN server will use.
	Certificate pulumi.StringPtrInput
	// Allowed ciphers.
	Cipher pulumi.StringPtrInput
	// Default profile to use.
	DefaultProfile pulumi.StringPtrInput
	// Specifies if IPv6 IP tunneling mode should be possible with this OVPN server.
	EnableTunIpv6 pulumi.BoolPtrInput
	// Defines whether the OVPN server is enabled or not.
	Enabled pulumi.BoolPtrInput
	// Length of IPv6 prefix for IPv6 address which will be used when generating OVPN interface on the server side.
	Ipv6PrefixLen pulumi.IntPtrInput
	// Defines  the time period (in seconds) after which the router is starting to send  keepalive packets every second. If no traffic and no keepalive  responses have come for that period of time (i.e. 2 *  keepalive-timeout), not responding client is proclaimed disconnected
	KeepaliveTimeout pulumi.StringPtrInput
	// Automatically generated MAC address of the server.
	MacAddress pulumi.StringPtrInput
	// Maximum Transmission Unit. Max packet size that the OVPN interface will be able to send without packet fragmentation.
	MaxMtu pulumi.IntPtrInput
	// Layer3 or layer2 tunnel mode (alternatively tun, tap)
	Mode pulumi.StringPtrInput
	// Subnet mask to be applied to the client.
	Netmask pulumi.IntPtrInput
	// Port to run the server on.
	Port pulumi.IntPtrInput
	// indicates the protocol to use when connecting with the remote endpoint.
	Protocol pulumi.StringPtrInput
	// Specifies what kind of routes the OVPN client must add to the routing table. def1 – Use this flag to override the default gateway by using 0.0.0.0/1 and  128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of overriding  but not wiping out the original default gateway. disabled - Do not send redirect-gateway flags to the OVPN client. ipv6 - Redirect IPv6 routing into the tunnel on the client side. This works  similarly to the def1 flag, that is, more specific IPv6 routes are added  (2000::/4 and 3000::/4), covering the whole IPv6 unicast space.
	RedirectGateway pulumi.StringPtrInput
	// Renegotiate data channel key after n seconds (default=3600).
	RenegSec pulumi.IntPtrInput
	// If set to yes, then the server checks whether the client's certificate belongs to the same certificate chain.
	RequireClientCertificate pulumi.BoolPtrInput
	// Specifies which TLS versions to allow.
	TlsVersion pulumi.StringPtrInput
	// IPv6 prefix address which will be used when generating the OVPN interface on the server side.
	TunServerIpv6 pulumi.StringPtrInput
}

func (ResourceOpenVPNServerState) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceOpenVPNServerState)(nil)).Elem()
}

type resourceOpenVPNServerArgs struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ *int `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ *string `pulumi:"___path_"`
	// Authentication methods that the server will accept.
	Auth *string `pulumi:"auth"`
	// Name of the certificate that the OVPN server will use.
	Certificate string `pulumi:"certificate"`
	// Allowed ciphers.
	Cipher *string `pulumi:"cipher"`
	// Default profile to use.
	DefaultProfile *string `pulumi:"defaultProfile"`
	// Specifies if IPv6 IP tunneling mode should be possible with this OVPN server.
	EnableTunIpv6 *bool `pulumi:"enableTunIpv6"`
	// Defines whether the OVPN server is enabled or not.
	Enabled *bool `pulumi:"enabled"`
	// Length of IPv6 prefix for IPv6 address which will be used when generating OVPN interface on the server side.
	Ipv6PrefixLen *int `pulumi:"ipv6PrefixLen"`
	// Defines  the time period (in seconds) after which the router is starting to send  keepalive packets every second. If no traffic and no keepalive  responses have come for that period of time (i.e. 2 *  keepalive-timeout), not responding client is proclaimed disconnected
	KeepaliveTimeout *string `pulumi:"keepaliveTimeout"`
	// Automatically generated MAC address of the server.
	MacAddress *string `pulumi:"macAddress"`
	// Maximum Transmission Unit. Max packet size that the OVPN interface will be able to send without packet fragmentation.
	MaxMtu *int `pulumi:"maxMtu"`
	// Layer3 or layer2 tunnel mode (alternatively tun, tap)
	Mode *string `pulumi:"mode"`
	// Subnet mask to be applied to the client.
	Netmask *int `pulumi:"netmask"`
	// Port to run the server on.
	Port *int `pulumi:"port"`
	// indicates the protocol to use when connecting with the remote endpoint.
	Protocol *string `pulumi:"protocol"`
	// Specifies what kind of routes the OVPN client must add to the routing table. def1 – Use this flag to override the default gateway by using 0.0.0.0/1 and  128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of overriding  but not wiping out the original default gateway. disabled - Do not send redirect-gateway flags to the OVPN client. ipv6 - Redirect IPv6 routing into the tunnel on the client side. This works  similarly to the def1 flag, that is, more specific IPv6 routes are added  (2000::/4 and 3000::/4), covering the whole IPv6 unicast space.
	RedirectGateway *string `pulumi:"redirectGateway"`
	// Renegotiate data channel key after n seconds (default=3600).
	RenegSec *int `pulumi:"renegSec"`
	// If set to yes, then the server checks whether the client's certificate belongs to the same certificate chain.
	RequireClientCertificate *bool `pulumi:"requireClientCertificate"`
	// Specifies which TLS versions to allow.
	TlsVersion *string `pulumi:"tlsVersion"`
	// IPv6 prefix address which will be used when generating the OVPN interface on the server side.
	TunServerIpv6 *string `pulumi:"tunServerIpv6"`
}

// The set of arguments for constructing a ResourceOpenVPNServer resource.
type ResourceOpenVPNServerArgs struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrInput
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrInput
	// Authentication methods that the server will accept.
	Auth pulumi.StringPtrInput
	// Name of the certificate that the OVPN server will use.
	Certificate pulumi.StringInput
	// Allowed ciphers.
	Cipher pulumi.StringPtrInput
	// Default profile to use.
	DefaultProfile pulumi.StringPtrInput
	// Specifies if IPv6 IP tunneling mode should be possible with this OVPN server.
	EnableTunIpv6 pulumi.BoolPtrInput
	// Defines whether the OVPN server is enabled or not.
	Enabled pulumi.BoolPtrInput
	// Length of IPv6 prefix for IPv6 address which will be used when generating OVPN interface on the server side.
	Ipv6PrefixLen pulumi.IntPtrInput
	// Defines  the time period (in seconds) after which the router is starting to send  keepalive packets every second. If no traffic and no keepalive  responses have come for that period of time (i.e. 2 *  keepalive-timeout), not responding client is proclaimed disconnected
	KeepaliveTimeout pulumi.StringPtrInput
	// Automatically generated MAC address of the server.
	MacAddress pulumi.StringPtrInput
	// Maximum Transmission Unit. Max packet size that the OVPN interface will be able to send without packet fragmentation.
	MaxMtu pulumi.IntPtrInput
	// Layer3 or layer2 tunnel mode (alternatively tun, tap)
	Mode pulumi.StringPtrInput
	// Subnet mask to be applied to the client.
	Netmask pulumi.IntPtrInput
	// Port to run the server on.
	Port pulumi.IntPtrInput
	// indicates the protocol to use when connecting with the remote endpoint.
	Protocol pulumi.StringPtrInput
	// Specifies what kind of routes the OVPN client must add to the routing table. def1 – Use this flag to override the default gateway by using 0.0.0.0/1 and  128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of overriding  but not wiping out the original default gateway. disabled - Do not send redirect-gateway flags to the OVPN client. ipv6 - Redirect IPv6 routing into the tunnel on the client side. This works  similarly to the def1 flag, that is, more specific IPv6 routes are added  (2000::/4 and 3000::/4), covering the whole IPv6 unicast space.
	RedirectGateway pulumi.StringPtrInput
	// Renegotiate data channel key after n seconds (default=3600).
	RenegSec pulumi.IntPtrInput
	// If set to yes, then the server checks whether the client's certificate belongs to the same certificate chain.
	RequireClientCertificate pulumi.BoolPtrInput
	// Specifies which TLS versions to allow.
	TlsVersion pulumi.StringPtrInput
	// IPv6 prefix address which will be used when generating the OVPN interface on the server side.
	TunServerIpv6 pulumi.StringPtrInput
}

func (ResourceOpenVPNServerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceOpenVPNServerArgs)(nil)).Elem()
}

type ResourceOpenVPNServerInput interface {
	pulumi.Input

	ToResourceOpenVPNServerOutput() ResourceOpenVPNServerOutput
	ToResourceOpenVPNServerOutputWithContext(ctx context.Context) ResourceOpenVPNServerOutput
}

func (*ResourceOpenVPNServer) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceOpenVPNServer)(nil)).Elem()
}

func (i *ResourceOpenVPNServer) ToResourceOpenVPNServerOutput() ResourceOpenVPNServerOutput {
	return i.ToResourceOpenVPNServerOutputWithContext(context.Background())
}

func (i *ResourceOpenVPNServer) ToResourceOpenVPNServerOutputWithContext(ctx context.Context) ResourceOpenVPNServerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceOpenVPNServerOutput)
}

// ResourceOpenVPNServerArrayInput is an input type that accepts ResourceOpenVPNServerArray and ResourceOpenVPNServerArrayOutput values.
// You can construct a concrete instance of `ResourceOpenVPNServerArrayInput` via:
//
//	ResourceOpenVPNServerArray{ ResourceOpenVPNServerArgs{...} }
type ResourceOpenVPNServerArrayInput interface {
	pulumi.Input

	ToResourceOpenVPNServerArrayOutput() ResourceOpenVPNServerArrayOutput
	ToResourceOpenVPNServerArrayOutputWithContext(context.Context) ResourceOpenVPNServerArrayOutput
}

type ResourceOpenVPNServerArray []ResourceOpenVPNServerInput

func (ResourceOpenVPNServerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ResourceOpenVPNServer)(nil)).Elem()
}

func (i ResourceOpenVPNServerArray) ToResourceOpenVPNServerArrayOutput() ResourceOpenVPNServerArrayOutput {
	return i.ToResourceOpenVPNServerArrayOutputWithContext(context.Background())
}

func (i ResourceOpenVPNServerArray) ToResourceOpenVPNServerArrayOutputWithContext(ctx context.Context) ResourceOpenVPNServerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceOpenVPNServerArrayOutput)
}

// ResourceOpenVPNServerMapInput is an input type that accepts ResourceOpenVPNServerMap and ResourceOpenVPNServerMapOutput values.
// You can construct a concrete instance of `ResourceOpenVPNServerMapInput` via:
//
//	ResourceOpenVPNServerMap{ "key": ResourceOpenVPNServerArgs{...} }
type ResourceOpenVPNServerMapInput interface {
	pulumi.Input

	ToResourceOpenVPNServerMapOutput() ResourceOpenVPNServerMapOutput
	ToResourceOpenVPNServerMapOutputWithContext(context.Context) ResourceOpenVPNServerMapOutput
}

type ResourceOpenVPNServerMap map[string]ResourceOpenVPNServerInput

func (ResourceOpenVPNServerMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ResourceOpenVPNServer)(nil)).Elem()
}

func (i ResourceOpenVPNServerMap) ToResourceOpenVPNServerMapOutput() ResourceOpenVPNServerMapOutput {
	return i.ToResourceOpenVPNServerMapOutputWithContext(context.Background())
}

func (i ResourceOpenVPNServerMap) ToResourceOpenVPNServerMapOutputWithContext(ctx context.Context) ResourceOpenVPNServerMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceOpenVPNServerMapOutput)
}

type ResourceOpenVPNServerOutput struct{ *pulumi.OutputState }

func (ResourceOpenVPNServerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceOpenVPNServer)(nil)).Elem()
}

func (o ResourceOpenVPNServerOutput) ToResourceOpenVPNServerOutput() ResourceOpenVPNServerOutput {
	return o
}

func (o ResourceOpenVPNServerOutput) ToResourceOpenVPNServerOutputWithContext(ctx context.Context) ResourceOpenVPNServerOutput {
	return o
}

// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
func (o ResourceOpenVPNServerOutput) ___id_() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.IntPtrOutput { return v.___id_ }).(pulumi.IntPtrOutput)
}

// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
func (o ResourceOpenVPNServerOutput) ___path_() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.StringPtrOutput { return v.___path_ }).(pulumi.StringPtrOutput)
}

// Authentication methods that the server will accept.
func (o ResourceOpenVPNServerOutput) Auth() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.StringPtrOutput { return v.Auth }).(pulumi.StringPtrOutput)
}

// Name of the certificate that the OVPN server will use.
func (o ResourceOpenVPNServerOutput) Certificate() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.StringOutput { return v.Certificate }).(pulumi.StringOutput)
}

// Allowed ciphers.
func (o ResourceOpenVPNServerOutput) Cipher() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.StringPtrOutput { return v.Cipher }).(pulumi.StringPtrOutput)
}

// Default profile to use.
func (o ResourceOpenVPNServerOutput) DefaultProfile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.StringPtrOutput { return v.DefaultProfile }).(pulumi.StringPtrOutput)
}

// Specifies if IPv6 IP tunneling mode should be possible with this OVPN server.
func (o ResourceOpenVPNServerOutput) EnableTunIpv6() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.BoolPtrOutput { return v.EnableTunIpv6 }).(pulumi.BoolPtrOutput)
}

// Defines whether the OVPN server is enabled or not.
func (o ResourceOpenVPNServerOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// Length of IPv6 prefix for IPv6 address which will be used when generating OVPN interface on the server side.
func (o ResourceOpenVPNServerOutput) Ipv6PrefixLen() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.IntPtrOutput { return v.Ipv6PrefixLen }).(pulumi.IntPtrOutput)
}

// Defines  the time period (in seconds) after which the router is starting to send  keepalive packets every second. If no traffic and no keepalive  responses have come for that period of time (i.e. 2 *  keepalive-timeout), not responding client is proclaimed disconnected
func (o ResourceOpenVPNServerOutput) KeepaliveTimeout() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.StringPtrOutput { return v.KeepaliveTimeout }).(pulumi.StringPtrOutput)
}

// Automatically generated MAC address of the server.
func (o ResourceOpenVPNServerOutput) MacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.StringOutput { return v.MacAddress }).(pulumi.StringOutput)
}

// Maximum Transmission Unit. Max packet size that the OVPN interface will be able to send without packet fragmentation.
func (o ResourceOpenVPNServerOutput) MaxMtu() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.IntPtrOutput { return v.MaxMtu }).(pulumi.IntPtrOutput)
}

// Layer3 or layer2 tunnel mode (alternatively tun, tap)
func (o ResourceOpenVPNServerOutput) Mode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.StringPtrOutput { return v.Mode }).(pulumi.StringPtrOutput)
}

// Subnet mask to be applied to the client.
func (o ResourceOpenVPNServerOutput) Netmask() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.IntPtrOutput { return v.Netmask }).(pulumi.IntPtrOutput)
}

// Port to run the server on.
func (o ResourceOpenVPNServerOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.IntPtrOutput { return v.Port }).(pulumi.IntPtrOutput)
}

// indicates the protocol to use when connecting with the remote endpoint.
func (o ResourceOpenVPNServerOutput) Protocol() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.StringPtrOutput { return v.Protocol }).(pulumi.StringPtrOutput)
}

// Specifies what kind of routes the OVPN client must add to the routing table. def1 – Use this flag to override the default gateway by using 0.0.0.0/1 and  128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of overriding  but not wiping out the original default gateway. disabled - Do not send redirect-gateway flags to the OVPN client. ipv6 - Redirect IPv6 routing into the tunnel on the client side. This works  similarly to the def1 flag, that is, more specific IPv6 routes are added  (2000::/4 and 3000::/4), covering the whole IPv6 unicast space.
func (o ResourceOpenVPNServerOutput) RedirectGateway() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.StringPtrOutput { return v.RedirectGateway }).(pulumi.StringPtrOutput)
}

// Renegotiate data channel key after n seconds (default=3600).
func (o ResourceOpenVPNServerOutput) RenegSec() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.IntPtrOutput { return v.RenegSec }).(pulumi.IntPtrOutput)
}

// If set to yes, then the server checks whether the client's certificate belongs to the same certificate chain.
func (o ResourceOpenVPNServerOutput) RequireClientCertificate() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.BoolPtrOutput { return v.RequireClientCertificate }).(pulumi.BoolPtrOutput)
}

// Specifies which TLS versions to allow.
func (o ResourceOpenVPNServerOutput) TlsVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.StringPtrOutput { return v.TlsVersion }).(pulumi.StringPtrOutput)
}

// IPv6 prefix address which will be used when generating the OVPN interface on the server side.
func (o ResourceOpenVPNServerOutput) TunServerIpv6() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceOpenVPNServer) pulumi.StringPtrOutput { return v.TunServerIpv6 }).(pulumi.StringPtrOutput)
}

type ResourceOpenVPNServerArrayOutput struct{ *pulumi.OutputState }

func (ResourceOpenVPNServerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ResourceOpenVPNServer)(nil)).Elem()
}

func (o ResourceOpenVPNServerArrayOutput) ToResourceOpenVPNServerArrayOutput() ResourceOpenVPNServerArrayOutput {
	return o
}

func (o ResourceOpenVPNServerArrayOutput) ToResourceOpenVPNServerArrayOutputWithContext(ctx context.Context) ResourceOpenVPNServerArrayOutput {
	return o
}

func (o ResourceOpenVPNServerArrayOutput) Index(i pulumi.IntInput) ResourceOpenVPNServerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ResourceOpenVPNServer {
		return vs[0].([]*ResourceOpenVPNServer)[vs[1].(int)]
	}).(ResourceOpenVPNServerOutput)
}

type ResourceOpenVPNServerMapOutput struct{ *pulumi.OutputState }

func (ResourceOpenVPNServerMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ResourceOpenVPNServer)(nil)).Elem()
}

func (o ResourceOpenVPNServerMapOutput) ToResourceOpenVPNServerMapOutput() ResourceOpenVPNServerMapOutput {
	return o
}

func (o ResourceOpenVPNServerMapOutput) ToResourceOpenVPNServerMapOutputWithContext(ctx context.Context) ResourceOpenVPNServerMapOutput {
	return o
}

func (o ResourceOpenVPNServerMapOutput) MapIndex(k pulumi.StringInput) ResourceOpenVPNServerOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ResourceOpenVPNServer {
		return vs[0].(map[string]*ResourceOpenVPNServer)[vs[1].(string)]
	}).(ResourceOpenVPNServerOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceOpenVPNServerInput)(nil)).Elem(), &ResourceOpenVPNServer{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceOpenVPNServerArrayInput)(nil)).Elem(), ResourceOpenVPNServerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceOpenVPNServerMapInput)(nil)).Elem(), ResourceOpenVPNServerMap{})
	pulumi.RegisterOutputType(ResourceOpenVPNServerOutput{})
	pulumi.RegisterOutputType(ResourceOpenVPNServerArrayOutput{})
	pulumi.RegisterOutputType(ResourceOpenVPNServerMapOutput{})
}
