// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package routeros

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-routeros/sdk/go/routeros"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := routeros.NewResourceCapsManManagerInterface(ctx, "testManagerInterface", &routeros.ResourceCapsManManagerInterfaceArgs{
//				Forbid:    pulumi.Bool(true),
//				Interface: pulumi.String("ether1"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// #The ID can be found via API or the terminal #The command for the terminal is ->
//
// :put [/caps-man/manager/interface get [print show-ids]]
//
// ```sh
//
//	$ pulumi import routeros:index/resourceCapsManManagerInterface:ResourceCapsManManagerInterface test_manager_interface "*6"
//
// ```
type ResourceCapsManManagerInterface struct {
	pulumi.CustomResourceState

	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrOutput `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrOutput `pulumi:"___path_"`
	Comment  pulumi.StringPtrOutput `pulumi:"comment"`
	Default  pulumi.BoolOutput      `pulumi:"default"`
	Disabled pulumi.BoolPtrOutput   `pulumi:"disabled"`
	// Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
	Dynamic pulumi.BoolOutput `pulumi:"dynamic"`
	// Disable interface listening.
	Forbid pulumi.BoolPtrOutput `pulumi:"forbid"`
	// Name of the interface.
	Interface pulumi.StringOutput `pulumi:"interface"`
}

// NewResourceCapsManManagerInterface registers a new resource with the given unique name, arguments, and options.
func NewResourceCapsManManagerInterface(ctx *pulumi.Context,
	name string, args *ResourceCapsManManagerInterfaceArgs, opts ...pulumi.ResourceOption) (*ResourceCapsManManagerInterface, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Interface == nil {
		return nil, errors.New("invalid value for required argument 'Interface'")
	}
	var resource ResourceCapsManManagerInterface
	err := ctx.RegisterResource("routeros:index/resourceCapsManManagerInterface:ResourceCapsManManagerInterface", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetResourceCapsManManagerInterface gets an existing ResourceCapsManManagerInterface resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetResourceCapsManManagerInterface(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ResourceCapsManManagerInterfaceState, opts ...pulumi.ResourceOption) (*ResourceCapsManManagerInterface, error) {
	var resource ResourceCapsManManagerInterface
	err := ctx.ReadResource("routeros:index/resourceCapsManManagerInterface:ResourceCapsManManagerInterface", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ResourceCapsManManagerInterface resources.
type resourceCapsManManagerInterfaceState struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ *int `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ *string `pulumi:"___path_"`
	Comment  *string `pulumi:"comment"`
	Default  *bool   `pulumi:"default"`
	Disabled *bool   `pulumi:"disabled"`
	// Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
	Dynamic *bool `pulumi:"dynamic"`
	// Disable interface listening.
	Forbid *bool `pulumi:"forbid"`
	// Name of the interface.
	Interface *string `pulumi:"interface"`
}

type ResourceCapsManManagerInterfaceState struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrInput
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrInput
	Comment  pulumi.StringPtrInput
	Default  pulumi.BoolPtrInput
	Disabled pulumi.BoolPtrInput
	// Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
	Dynamic pulumi.BoolPtrInput
	// Disable interface listening.
	Forbid pulumi.BoolPtrInput
	// Name of the interface.
	Interface pulumi.StringPtrInput
}

func (ResourceCapsManManagerInterfaceState) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceCapsManManagerInterfaceState)(nil)).Elem()
}

type resourceCapsManManagerInterfaceArgs struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ *int `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ *string `pulumi:"___path_"`
	Comment  *string `pulumi:"comment"`
	Disabled *bool   `pulumi:"disabled"`
	// Disable interface listening.
	Forbid *bool `pulumi:"forbid"`
	// Name of the interface.
	Interface string `pulumi:"interface"`
}

// The set of arguments for constructing a ResourceCapsManManagerInterface resource.
type ResourceCapsManManagerInterfaceArgs struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrInput
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrInput
	Comment  pulumi.StringPtrInput
	Disabled pulumi.BoolPtrInput
	// Disable interface listening.
	Forbid pulumi.BoolPtrInput
	// Name of the interface.
	Interface pulumi.StringInput
}

func (ResourceCapsManManagerInterfaceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceCapsManManagerInterfaceArgs)(nil)).Elem()
}

type ResourceCapsManManagerInterfaceInput interface {
	pulumi.Input

	ToResourceCapsManManagerInterfaceOutput() ResourceCapsManManagerInterfaceOutput
	ToResourceCapsManManagerInterfaceOutputWithContext(ctx context.Context) ResourceCapsManManagerInterfaceOutput
}

func (*ResourceCapsManManagerInterface) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceCapsManManagerInterface)(nil)).Elem()
}

func (i *ResourceCapsManManagerInterface) ToResourceCapsManManagerInterfaceOutput() ResourceCapsManManagerInterfaceOutput {
	return i.ToResourceCapsManManagerInterfaceOutputWithContext(context.Background())
}

func (i *ResourceCapsManManagerInterface) ToResourceCapsManManagerInterfaceOutputWithContext(ctx context.Context) ResourceCapsManManagerInterfaceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceCapsManManagerInterfaceOutput)
}

// ResourceCapsManManagerInterfaceArrayInput is an input type that accepts ResourceCapsManManagerInterfaceArray and ResourceCapsManManagerInterfaceArrayOutput values.
// You can construct a concrete instance of `ResourceCapsManManagerInterfaceArrayInput` via:
//
//	ResourceCapsManManagerInterfaceArray{ ResourceCapsManManagerInterfaceArgs{...} }
type ResourceCapsManManagerInterfaceArrayInput interface {
	pulumi.Input

	ToResourceCapsManManagerInterfaceArrayOutput() ResourceCapsManManagerInterfaceArrayOutput
	ToResourceCapsManManagerInterfaceArrayOutputWithContext(context.Context) ResourceCapsManManagerInterfaceArrayOutput
}

type ResourceCapsManManagerInterfaceArray []ResourceCapsManManagerInterfaceInput

func (ResourceCapsManManagerInterfaceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ResourceCapsManManagerInterface)(nil)).Elem()
}

func (i ResourceCapsManManagerInterfaceArray) ToResourceCapsManManagerInterfaceArrayOutput() ResourceCapsManManagerInterfaceArrayOutput {
	return i.ToResourceCapsManManagerInterfaceArrayOutputWithContext(context.Background())
}

func (i ResourceCapsManManagerInterfaceArray) ToResourceCapsManManagerInterfaceArrayOutputWithContext(ctx context.Context) ResourceCapsManManagerInterfaceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceCapsManManagerInterfaceArrayOutput)
}

// ResourceCapsManManagerInterfaceMapInput is an input type that accepts ResourceCapsManManagerInterfaceMap and ResourceCapsManManagerInterfaceMapOutput values.
// You can construct a concrete instance of `ResourceCapsManManagerInterfaceMapInput` via:
//
//	ResourceCapsManManagerInterfaceMap{ "key": ResourceCapsManManagerInterfaceArgs{...} }
type ResourceCapsManManagerInterfaceMapInput interface {
	pulumi.Input

	ToResourceCapsManManagerInterfaceMapOutput() ResourceCapsManManagerInterfaceMapOutput
	ToResourceCapsManManagerInterfaceMapOutputWithContext(context.Context) ResourceCapsManManagerInterfaceMapOutput
}

type ResourceCapsManManagerInterfaceMap map[string]ResourceCapsManManagerInterfaceInput

func (ResourceCapsManManagerInterfaceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ResourceCapsManManagerInterface)(nil)).Elem()
}

func (i ResourceCapsManManagerInterfaceMap) ToResourceCapsManManagerInterfaceMapOutput() ResourceCapsManManagerInterfaceMapOutput {
	return i.ToResourceCapsManManagerInterfaceMapOutputWithContext(context.Background())
}

func (i ResourceCapsManManagerInterfaceMap) ToResourceCapsManManagerInterfaceMapOutputWithContext(ctx context.Context) ResourceCapsManManagerInterfaceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceCapsManManagerInterfaceMapOutput)
}

type ResourceCapsManManagerInterfaceOutput struct{ *pulumi.OutputState }

func (ResourceCapsManManagerInterfaceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceCapsManManagerInterface)(nil)).Elem()
}

func (o ResourceCapsManManagerInterfaceOutput) ToResourceCapsManManagerInterfaceOutput() ResourceCapsManManagerInterfaceOutput {
	return o
}

func (o ResourceCapsManManagerInterfaceOutput) ToResourceCapsManManagerInterfaceOutputWithContext(ctx context.Context) ResourceCapsManManagerInterfaceOutput {
	return o
}

// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
func (o ResourceCapsManManagerInterfaceOutput) ___id_() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ResourceCapsManManagerInterface) pulumi.IntPtrOutput { return v.___id_ }).(pulumi.IntPtrOutput)
}

// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
func (o ResourceCapsManManagerInterfaceOutput) ___path_() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceCapsManManagerInterface) pulumi.StringPtrOutput { return v.___path_ }).(pulumi.StringPtrOutput)
}

func (o ResourceCapsManManagerInterfaceOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceCapsManManagerInterface) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

func (o ResourceCapsManManagerInterfaceOutput) Default() pulumi.BoolOutput {
	return o.ApplyT(func(v *ResourceCapsManManagerInterface) pulumi.BoolOutput { return v.Default }).(pulumi.BoolOutput)
}

func (o ResourceCapsManManagerInterfaceOutput) Disabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ResourceCapsManManagerInterface) pulumi.BoolPtrOutput { return v.Disabled }).(pulumi.BoolPtrOutput)
}

// Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
func (o ResourceCapsManManagerInterfaceOutput) Dynamic() pulumi.BoolOutput {
	return o.ApplyT(func(v *ResourceCapsManManagerInterface) pulumi.BoolOutput { return v.Dynamic }).(pulumi.BoolOutput)
}

// Disable interface listening.
func (o ResourceCapsManManagerInterfaceOutput) Forbid() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ResourceCapsManManagerInterface) pulumi.BoolPtrOutput { return v.Forbid }).(pulumi.BoolPtrOutput)
}

// Name of the interface.
func (o ResourceCapsManManagerInterfaceOutput) Interface() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceCapsManManagerInterface) pulumi.StringOutput { return v.Interface }).(pulumi.StringOutput)
}

type ResourceCapsManManagerInterfaceArrayOutput struct{ *pulumi.OutputState }

func (ResourceCapsManManagerInterfaceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ResourceCapsManManagerInterface)(nil)).Elem()
}

func (o ResourceCapsManManagerInterfaceArrayOutput) ToResourceCapsManManagerInterfaceArrayOutput() ResourceCapsManManagerInterfaceArrayOutput {
	return o
}

func (o ResourceCapsManManagerInterfaceArrayOutput) ToResourceCapsManManagerInterfaceArrayOutputWithContext(ctx context.Context) ResourceCapsManManagerInterfaceArrayOutput {
	return o
}

func (o ResourceCapsManManagerInterfaceArrayOutput) Index(i pulumi.IntInput) ResourceCapsManManagerInterfaceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ResourceCapsManManagerInterface {
		return vs[0].([]*ResourceCapsManManagerInterface)[vs[1].(int)]
	}).(ResourceCapsManManagerInterfaceOutput)
}

type ResourceCapsManManagerInterfaceMapOutput struct{ *pulumi.OutputState }

func (ResourceCapsManManagerInterfaceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ResourceCapsManManagerInterface)(nil)).Elem()
}

func (o ResourceCapsManManagerInterfaceMapOutput) ToResourceCapsManManagerInterfaceMapOutput() ResourceCapsManManagerInterfaceMapOutput {
	return o
}

func (o ResourceCapsManManagerInterfaceMapOutput) ToResourceCapsManManagerInterfaceMapOutputWithContext(ctx context.Context) ResourceCapsManManagerInterfaceMapOutput {
	return o
}

func (o ResourceCapsManManagerInterfaceMapOutput) MapIndex(k pulumi.StringInput) ResourceCapsManManagerInterfaceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ResourceCapsManManagerInterface {
		return vs[0].(map[string]*ResourceCapsManManagerInterface)[vs[1].(string)]
	}).(ResourceCapsManManagerInterfaceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceCapsManManagerInterfaceInput)(nil)).Elem(), &ResourceCapsManManagerInterface{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceCapsManManagerInterfaceArrayInput)(nil)).Elem(), ResourceCapsManManagerInterfaceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceCapsManManagerInterfaceMapInput)(nil)).Elem(), ResourceCapsManManagerInterfaceMap{})
	pulumi.RegisterOutputType(ResourceCapsManManagerInterfaceOutput{})
	pulumi.RegisterOutputType(ResourceCapsManManagerInterfaceArrayOutput{})
	pulumi.RegisterOutputType(ResourceCapsManManagerInterfaceMapOutput{})
}
