// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package routeros

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-routeros/sdk/go/routeros"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := routeros.NewResourceCapsManAaa(ctx, "test3a", &routeros.ResourceCapsManAaaArgs{
//				CalledFormat: pulumi.String("ssid"),
//				MacMode:      pulumi.String("as-username-and-password"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
//
//	$ pulumi import routeros:index/resourceCapsManAaa:ResourceCapsManAaa test_3a .
//
// ```
type ResourceCapsManAaa struct {
	pulumi.CustomResourceState

	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrOutput `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrOutput `pulumi:"___path_"`
	// Format of how the 'called-id' identifier will be passed to RADIUS. When configuring radius server clients, you can specify 'called-id' in order to separate multiple entires.
	CalledFormat pulumi.StringPtrOutput `pulumi:"calledFormat"`
	// When RADIUS accounting is used, Access Point periodically sends accounting information updates to the RADIUS server. This property specifies the default update interval that can be overridden by the RADIUS server using the Acct-Interim-Interval attribute.
	InterimUpdate pulumi.StringOutput `pulumi:"interimUpdate"`
	// If this value is set to a time interval, the Access Point will cache RADIUS MAC authentication responses for a specified time, and will not contact the RADIUS server if matching cache entry already exists. The value disabled will disable the cache, Access Point will always contact the RADIUS server.
	MacCaching pulumi.StringOutput `pulumi:"macCaching"`
	// Controls how the MAC address of the client is encoded by Access Point in the User-Name attribute of the MAC authentication and MAC accounting RADIUS requests.
	MacFormat pulumi.StringPtrOutput `pulumi:"macFormat"`
	// By default Access Point uses an empty password, when sending Access-Request during MAC authentication. When this property is set to as-username-and-password, Access Point will use the same value for the User-Password attribute as for the User-Name attribute.
	MacMode pulumi.StringPtrOutput `pulumi:"macMode"`
}

// NewResourceCapsManAaa registers a new resource with the given unique name, arguments, and options.
func NewResourceCapsManAaa(ctx *pulumi.Context,
	name string, args *ResourceCapsManAaaArgs, opts ...pulumi.ResourceOption) (*ResourceCapsManAaa, error) {
	if args == nil {
		args = &ResourceCapsManAaaArgs{}
	}

	var resource ResourceCapsManAaa
	err := ctx.RegisterResource("routeros:index/resourceCapsManAaa:ResourceCapsManAaa", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetResourceCapsManAaa gets an existing ResourceCapsManAaa resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetResourceCapsManAaa(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ResourceCapsManAaaState, opts ...pulumi.ResourceOption) (*ResourceCapsManAaa, error) {
	var resource ResourceCapsManAaa
	err := ctx.ReadResource("routeros:index/resourceCapsManAaa:ResourceCapsManAaa", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ResourceCapsManAaa resources.
type resourceCapsManAaaState struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ *int `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ *string `pulumi:"___path_"`
	// Format of how the 'called-id' identifier will be passed to RADIUS. When configuring radius server clients, you can specify 'called-id' in order to separate multiple entires.
	CalledFormat *string `pulumi:"calledFormat"`
	// When RADIUS accounting is used, Access Point periodically sends accounting information updates to the RADIUS server. This property specifies the default update interval that can be overridden by the RADIUS server using the Acct-Interim-Interval attribute.
	InterimUpdate *string `pulumi:"interimUpdate"`
	// If this value is set to a time interval, the Access Point will cache RADIUS MAC authentication responses for a specified time, and will not contact the RADIUS server if matching cache entry already exists. The value disabled will disable the cache, Access Point will always contact the RADIUS server.
	MacCaching *string `pulumi:"macCaching"`
	// Controls how the MAC address of the client is encoded by Access Point in the User-Name attribute of the MAC authentication and MAC accounting RADIUS requests.
	MacFormat *string `pulumi:"macFormat"`
	// By default Access Point uses an empty password, when sending Access-Request during MAC authentication. When this property is set to as-username-and-password, Access Point will use the same value for the User-Password attribute as for the User-Name attribute.
	MacMode *string `pulumi:"macMode"`
}

type ResourceCapsManAaaState struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrInput
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrInput
	// Format of how the 'called-id' identifier will be passed to RADIUS. When configuring radius server clients, you can specify 'called-id' in order to separate multiple entires.
	CalledFormat pulumi.StringPtrInput
	// When RADIUS accounting is used, Access Point periodically sends accounting information updates to the RADIUS server. This property specifies the default update interval that can be overridden by the RADIUS server using the Acct-Interim-Interval attribute.
	InterimUpdate pulumi.StringPtrInput
	// If this value is set to a time interval, the Access Point will cache RADIUS MAC authentication responses for a specified time, and will not contact the RADIUS server if matching cache entry already exists. The value disabled will disable the cache, Access Point will always contact the RADIUS server.
	MacCaching pulumi.StringPtrInput
	// Controls how the MAC address of the client is encoded by Access Point in the User-Name attribute of the MAC authentication and MAC accounting RADIUS requests.
	MacFormat pulumi.StringPtrInput
	// By default Access Point uses an empty password, when sending Access-Request during MAC authentication. When this property is set to as-username-and-password, Access Point will use the same value for the User-Password attribute as for the User-Name attribute.
	MacMode pulumi.StringPtrInput
}

func (ResourceCapsManAaaState) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceCapsManAaaState)(nil)).Elem()
}

type resourceCapsManAaaArgs struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ *int `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ *string `pulumi:"___path_"`
	// Format of how the 'called-id' identifier will be passed to RADIUS. When configuring radius server clients, you can specify 'called-id' in order to separate multiple entires.
	CalledFormat *string `pulumi:"calledFormat"`
	// When RADIUS accounting is used, Access Point periodically sends accounting information updates to the RADIUS server. This property specifies the default update interval that can be overridden by the RADIUS server using the Acct-Interim-Interval attribute.
	InterimUpdate *string `pulumi:"interimUpdate"`
	// If this value is set to a time interval, the Access Point will cache RADIUS MAC authentication responses for a specified time, and will not contact the RADIUS server if matching cache entry already exists. The value disabled will disable the cache, Access Point will always contact the RADIUS server.
	MacCaching *string `pulumi:"macCaching"`
	// Controls how the MAC address of the client is encoded by Access Point in the User-Name attribute of the MAC authentication and MAC accounting RADIUS requests.
	MacFormat *string `pulumi:"macFormat"`
	// By default Access Point uses an empty password, when sending Access-Request during MAC authentication. When this property is set to as-username-and-password, Access Point will use the same value for the User-Password attribute as for the User-Name attribute.
	MacMode *string `pulumi:"macMode"`
}

// The set of arguments for constructing a ResourceCapsManAaa resource.
type ResourceCapsManAaaArgs struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrInput
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrInput
	// Format of how the 'called-id' identifier will be passed to RADIUS. When configuring radius server clients, you can specify 'called-id' in order to separate multiple entires.
	CalledFormat pulumi.StringPtrInput
	// When RADIUS accounting is used, Access Point periodically sends accounting information updates to the RADIUS server. This property specifies the default update interval that can be overridden by the RADIUS server using the Acct-Interim-Interval attribute.
	InterimUpdate pulumi.StringPtrInput
	// If this value is set to a time interval, the Access Point will cache RADIUS MAC authentication responses for a specified time, and will not contact the RADIUS server if matching cache entry already exists. The value disabled will disable the cache, Access Point will always contact the RADIUS server.
	MacCaching pulumi.StringPtrInput
	// Controls how the MAC address of the client is encoded by Access Point in the User-Name attribute of the MAC authentication and MAC accounting RADIUS requests.
	MacFormat pulumi.StringPtrInput
	// By default Access Point uses an empty password, when sending Access-Request during MAC authentication. When this property is set to as-username-and-password, Access Point will use the same value for the User-Password attribute as for the User-Name attribute.
	MacMode pulumi.StringPtrInput
}

func (ResourceCapsManAaaArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceCapsManAaaArgs)(nil)).Elem()
}

type ResourceCapsManAaaInput interface {
	pulumi.Input

	ToResourceCapsManAaaOutput() ResourceCapsManAaaOutput
	ToResourceCapsManAaaOutputWithContext(ctx context.Context) ResourceCapsManAaaOutput
}

func (*ResourceCapsManAaa) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceCapsManAaa)(nil)).Elem()
}

func (i *ResourceCapsManAaa) ToResourceCapsManAaaOutput() ResourceCapsManAaaOutput {
	return i.ToResourceCapsManAaaOutputWithContext(context.Background())
}

func (i *ResourceCapsManAaa) ToResourceCapsManAaaOutputWithContext(ctx context.Context) ResourceCapsManAaaOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceCapsManAaaOutput)
}

// ResourceCapsManAaaArrayInput is an input type that accepts ResourceCapsManAaaArray and ResourceCapsManAaaArrayOutput values.
// You can construct a concrete instance of `ResourceCapsManAaaArrayInput` via:
//
//	ResourceCapsManAaaArray{ ResourceCapsManAaaArgs{...} }
type ResourceCapsManAaaArrayInput interface {
	pulumi.Input

	ToResourceCapsManAaaArrayOutput() ResourceCapsManAaaArrayOutput
	ToResourceCapsManAaaArrayOutputWithContext(context.Context) ResourceCapsManAaaArrayOutput
}

type ResourceCapsManAaaArray []ResourceCapsManAaaInput

func (ResourceCapsManAaaArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ResourceCapsManAaa)(nil)).Elem()
}

func (i ResourceCapsManAaaArray) ToResourceCapsManAaaArrayOutput() ResourceCapsManAaaArrayOutput {
	return i.ToResourceCapsManAaaArrayOutputWithContext(context.Background())
}

func (i ResourceCapsManAaaArray) ToResourceCapsManAaaArrayOutputWithContext(ctx context.Context) ResourceCapsManAaaArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceCapsManAaaArrayOutput)
}

// ResourceCapsManAaaMapInput is an input type that accepts ResourceCapsManAaaMap and ResourceCapsManAaaMapOutput values.
// You can construct a concrete instance of `ResourceCapsManAaaMapInput` via:
//
//	ResourceCapsManAaaMap{ "key": ResourceCapsManAaaArgs{...} }
type ResourceCapsManAaaMapInput interface {
	pulumi.Input

	ToResourceCapsManAaaMapOutput() ResourceCapsManAaaMapOutput
	ToResourceCapsManAaaMapOutputWithContext(context.Context) ResourceCapsManAaaMapOutput
}

type ResourceCapsManAaaMap map[string]ResourceCapsManAaaInput

func (ResourceCapsManAaaMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ResourceCapsManAaa)(nil)).Elem()
}

func (i ResourceCapsManAaaMap) ToResourceCapsManAaaMapOutput() ResourceCapsManAaaMapOutput {
	return i.ToResourceCapsManAaaMapOutputWithContext(context.Background())
}

func (i ResourceCapsManAaaMap) ToResourceCapsManAaaMapOutputWithContext(ctx context.Context) ResourceCapsManAaaMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceCapsManAaaMapOutput)
}

type ResourceCapsManAaaOutput struct{ *pulumi.OutputState }

func (ResourceCapsManAaaOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceCapsManAaa)(nil)).Elem()
}

func (o ResourceCapsManAaaOutput) ToResourceCapsManAaaOutput() ResourceCapsManAaaOutput {
	return o
}

func (o ResourceCapsManAaaOutput) ToResourceCapsManAaaOutputWithContext(ctx context.Context) ResourceCapsManAaaOutput {
	return o
}

// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
func (o ResourceCapsManAaaOutput) ___id_() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ResourceCapsManAaa) pulumi.IntPtrOutput { return v.___id_ }).(pulumi.IntPtrOutput)
}

// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
func (o ResourceCapsManAaaOutput) ___path_() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceCapsManAaa) pulumi.StringPtrOutput { return v.___path_ }).(pulumi.StringPtrOutput)
}

// Format of how the 'called-id' identifier will be passed to RADIUS. When configuring radius server clients, you can specify 'called-id' in order to separate multiple entires.
func (o ResourceCapsManAaaOutput) CalledFormat() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceCapsManAaa) pulumi.StringPtrOutput { return v.CalledFormat }).(pulumi.StringPtrOutput)
}

// When RADIUS accounting is used, Access Point periodically sends accounting information updates to the RADIUS server. This property specifies the default update interval that can be overridden by the RADIUS server using the Acct-Interim-Interval attribute.
func (o ResourceCapsManAaaOutput) InterimUpdate() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceCapsManAaa) pulumi.StringOutput { return v.InterimUpdate }).(pulumi.StringOutput)
}

// If this value is set to a time interval, the Access Point will cache RADIUS MAC authentication responses for a specified time, and will not contact the RADIUS server if matching cache entry already exists. The value disabled will disable the cache, Access Point will always contact the RADIUS server.
func (o ResourceCapsManAaaOutput) MacCaching() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceCapsManAaa) pulumi.StringOutput { return v.MacCaching }).(pulumi.StringOutput)
}

// Controls how the MAC address of the client is encoded by Access Point in the User-Name attribute of the MAC authentication and MAC accounting RADIUS requests.
func (o ResourceCapsManAaaOutput) MacFormat() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceCapsManAaa) pulumi.StringPtrOutput { return v.MacFormat }).(pulumi.StringPtrOutput)
}

// By default Access Point uses an empty password, when sending Access-Request during MAC authentication. When this property is set to as-username-and-password, Access Point will use the same value for the User-Password attribute as for the User-Name attribute.
func (o ResourceCapsManAaaOutput) MacMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceCapsManAaa) pulumi.StringPtrOutput { return v.MacMode }).(pulumi.StringPtrOutput)
}

type ResourceCapsManAaaArrayOutput struct{ *pulumi.OutputState }

func (ResourceCapsManAaaArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ResourceCapsManAaa)(nil)).Elem()
}

func (o ResourceCapsManAaaArrayOutput) ToResourceCapsManAaaArrayOutput() ResourceCapsManAaaArrayOutput {
	return o
}

func (o ResourceCapsManAaaArrayOutput) ToResourceCapsManAaaArrayOutputWithContext(ctx context.Context) ResourceCapsManAaaArrayOutput {
	return o
}

func (o ResourceCapsManAaaArrayOutput) Index(i pulumi.IntInput) ResourceCapsManAaaOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ResourceCapsManAaa {
		return vs[0].([]*ResourceCapsManAaa)[vs[1].(int)]
	}).(ResourceCapsManAaaOutput)
}

type ResourceCapsManAaaMapOutput struct{ *pulumi.OutputState }

func (ResourceCapsManAaaMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ResourceCapsManAaa)(nil)).Elem()
}

func (o ResourceCapsManAaaMapOutput) ToResourceCapsManAaaMapOutput() ResourceCapsManAaaMapOutput {
	return o
}

func (o ResourceCapsManAaaMapOutput) ToResourceCapsManAaaMapOutputWithContext(ctx context.Context) ResourceCapsManAaaMapOutput {
	return o
}

func (o ResourceCapsManAaaMapOutput) MapIndex(k pulumi.StringInput) ResourceCapsManAaaOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ResourceCapsManAaa {
		return vs[0].(map[string]*ResourceCapsManAaa)[vs[1].(string)]
	}).(ResourceCapsManAaaOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceCapsManAaaInput)(nil)).Elem(), &ResourceCapsManAaa{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceCapsManAaaArrayInput)(nil)).Elem(), ResourceCapsManAaaArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceCapsManAaaMapInput)(nil)).Elem(), ResourceCapsManAaaMap{})
	pulumi.RegisterOutputType(ResourceCapsManAaaOutput{})
	pulumi.RegisterOutputType(ResourceCapsManAaaArrayOutput{})
	pulumi.RegisterOutputType(ResourceCapsManAaaMapOutput{})
}
