// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package routeros

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # ResourceDhcpServerLease (Resource)
//
// Creates a DHCP lease on the mikrotik device.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-routeros/sdk/go/routeros"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := routeros.NewResourceDhcpServerLease(ctx, "dhcpLease", &routeros.ResourceDhcpServerLeaseArgs{
//				Address:    pulumi.String("10.0.0.2"),
//				MacAddress: pulumi.String("AA:BB:CC:DD:11:22"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// #The ID can be found via API or the terminal #The command for the terminal is -> :put [/ip/dhcp-server/lease get [print show-ids]]
//
// ```sh
//
//	$ pulumi import routeros:index/resourceDhcpServerLease:ResourceDhcpServerLease dhcp_lease "*0"
//
// ```
type ResourceDhcpServerLease struct {
	pulumi.CustomResourceState

	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrOutput `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrOutput `pulumi:"___path_"`
	// The IP address of the machine currently holding the DHCP lease.
	ActiveAddress pulumi.StringOutput `pulumi:"activeAddress"`
	// Actual client-id of the client.
	ActiveClientId pulumi.StringOutput `pulumi:"activeClientId"`
	// The hostname of the machine currently holding the DHCP lease.
	ActiveHostname pulumi.StringOutput `pulumi:"activeHostname"`
	// The MAC address of of the machine currently holding the DHCP lease.
	ActiveMacAddress pulumi.StringOutput `pulumi:"activeMacAddress"`
	// Actual dhcp server, which serves this client.
	ActiveServer pulumi.StringOutput `pulumi:"activeServer"`
	// The IP address of the DHCP lease to be created.
	Address pulumi.StringOutput `pulumi:"address"`
	// Address list to which address will be added if lease is bound.
	AddressLists pulumi.StringPtrOutput `pulumi:"addressLists"`
	// Circuit ID of DHCP relay agent. If each character should be valid ASCII text symbol or else this value is displayed as hex dump.
	AgentCircuitId pulumi.StringOutput `pulumi:"agentCircuitId"`
	// Remote ID, set by DHCP relay agent.
	AgentRemoteId pulumi.StringOutput `pulumi:"agentRemoteId"`
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	AllowDualStackQueue pulumi.BoolPtrOutput `pulumi:"allowDualStackQueue"`
	// Send all replies as broadcasts.
	AlwaysBroadcast pulumi.BoolPtrOutput `pulumi:"alwaysBroadcast"`
	// Whether to block access for this DHCP client (true|false).
	BlockAccess pulumi.BoolPtrOutput `pulumi:"blockAccess"`
	// Whether the lease is blocked.
	Blocked pulumi.BoolOutput `pulumi:"blocked"`
	// If specified, must match DHCP 'client identifier' option of the request.
	ClientId pulumi.StringPtrOutput `pulumi:"clientId"`
	Comment  pulumi.StringPtrOutput `pulumi:"comment"`
	// Add additional DHCP options.
	DhcpOption pulumi.StringPtrOutput `pulumi:"dhcpOption"`
	// Add additional set of DHCP options.
	DhcpOptionSet pulumi.StringPtrOutput `pulumi:"dhcpOptionSet"`
	Disabled      pulumi.BoolPtrOutput   `pulumi:"disabled"`
	// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device. Defaults to false.
	Dynamic pulumi.BoolPtrOutput `pulumi:"dynamic"`
	// Time until lease expires.
	ExpiresAfter pulumi.StringOutput `pulumi:"expiresAfter"`
	// The hostname of the device
	HostName pulumi.StringOutput `pulumi:"hostName"`
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	InsertQueueBefore pulumi.StringPtrOutput `pulumi:"insertQueueBefore"`
	LastSeen          pulumi.StringOutput    `pulumi:"lastSeen"`
	// Time that the client may use the address. If set to 0s lease will never expire.
	LeaseTime pulumi.StringPtrOutput `pulumi:"leaseTime"`
	// The MAC addreess of the DHCP lease to be created.
	MacAddress pulumi.StringOutput `pulumi:"macAddress"`
	// Shows if this dynamic lease is authenticated by RADIUS or not.
	Radius pulumi.StringOutput `pulumi:"radius"`
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	RateLimit pulumi.StringPtrOutput `pulumi:"rateLimit"`
	// Server name which serves this client.
	Server pulumi.StringPtrOutput `pulumi:"server"`
	// Source MAC address.
	SrcMacAddress pulumi.StringOutput `pulumi:"srcMacAddress"`
	// Lease status.
	Status pulumi.StringOutput `pulumi:"status"`
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	UseSrcMac pulumi.BoolPtrOutput `pulumi:"useSrcMac"`
}

// NewResourceDhcpServerLease registers a new resource with the given unique name, arguments, and options.
func NewResourceDhcpServerLease(ctx *pulumi.Context,
	name string, args *ResourceDhcpServerLeaseArgs, opts ...pulumi.ResourceOption) (*ResourceDhcpServerLease, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Address == nil {
		return nil, errors.New("invalid value for required argument 'Address'")
	}
	if args.MacAddress == nil {
		return nil, errors.New("invalid value for required argument 'MacAddress'")
	}
	var resource ResourceDhcpServerLease
	err := ctx.RegisterResource("routeros:index/resourceDhcpServerLease:ResourceDhcpServerLease", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetResourceDhcpServerLease gets an existing ResourceDhcpServerLease resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetResourceDhcpServerLease(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ResourceDhcpServerLeaseState, opts ...pulumi.ResourceOption) (*ResourceDhcpServerLease, error) {
	var resource ResourceDhcpServerLease
	err := ctx.ReadResource("routeros:index/resourceDhcpServerLease:ResourceDhcpServerLease", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ResourceDhcpServerLease resources.
type resourceDhcpServerLeaseState struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ *int `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ *string `pulumi:"___path_"`
	// The IP address of the machine currently holding the DHCP lease.
	ActiveAddress *string `pulumi:"activeAddress"`
	// Actual client-id of the client.
	ActiveClientId *string `pulumi:"activeClientId"`
	// The hostname of the machine currently holding the DHCP lease.
	ActiveHostname *string `pulumi:"activeHostname"`
	// The MAC address of of the machine currently holding the DHCP lease.
	ActiveMacAddress *string `pulumi:"activeMacAddress"`
	// Actual dhcp server, which serves this client.
	ActiveServer *string `pulumi:"activeServer"`
	// The IP address of the DHCP lease to be created.
	Address *string `pulumi:"address"`
	// Address list to which address will be added if lease is bound.
	AddressLists *string `pulumi:"addressLists"`
	// Circuit ID of DHCP relay agent. If each character should be valid ASCII text symbol or else this value is displayed as hex dump.
	AgentCircuitId *string `pulumi:"agentCircuitId"`
	// Remote ID, set by DHCP relay agent.
	AgentRemoteId *string `pulumi:"agentRemoteId"`
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	AllowDualStackQueue *bool `pulumi:"allowDualStackQueue"`
	// Send all replies as broadcasts.
	AlwaysBroadcast *bool `pulumi:"alwaysBroadcast"`
	// Whether to block access for this DHCP client (true|false).
	BlockAccess *bool `pulumi:"blockAccess"`
	// Whether the lease is blocked.
	Blocked *bool `pulumi:"blocked"`
	// If specified, must match DHCP 'client identifier' option of the request.
	ClientId *string `pulumi:"clientId"`
	Comment  *string `pulumi:"comment"`
	// Add additional DHCP options.
	DhcpOption *string `pulumi:"dhcpOption"`
	// Add additional set of DHCP options.
	DhcpOptionSet *string `pulumi:"dhcpOptionSet"`
	Disabled      *bool   `pulumi:"disabled"`
	// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device. Defaults to false.
	Dynamic *bool `pulumi:"dynamic"`
	// Time until lease expires.
	ExpiresAfter *string `pulumi:"expiresAfter"`
	// The hostname of the device
	HostName *string `pulumi:"hostName"`
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	InsertQueueBefore *string `pulumi:"insertQueueBefore"`
	LastSeen          *string `pulumi:"lastSeen"`
	// Time that the client may use the address. If set to 0s lease will never expire.
	LeaseTime *string `pulumi:"leaseTime"`
	// The MAC addreess of the DHCP lease to be created.
	MacAddress *string `pulumi:"macAddress"`
	// Shows if this dynamic lease is authenticated by RADIUS or not.
	Radius *string `pulumi:"radius"`
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	RateLimit *string `pulumi:"rateLimit"`
	// Server name which serves this client.
	Server *string `pulumi:"server"`
	// Source MAC address.
	SrcMacAddress *string `pulumi:"srcMacAddress"`
	// Lease status.
	Status *string `pulumi:"status"`
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	UseSrcMac *bool `pulumi:"useSrcMac"`
}

type ResourceDhcpServerLeaseState struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrInput
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrInput
	// The IP address of the machine currently holding the DHCP lease.
	ActiveAddress pulumi.StringPtrInput
	// Actual client-id of the client.
	ActiveClientId pulumi.StringPtrInput
	// The hostname of the machine currently holding the DHCP lease.
	ActiveHostname pulumi.StringPtrInput
	// The MAC address of of the machine currently holding the DHCP lease.
	ActiveMacAddress pulumi.StringPtrInput
	// Actual dhcp server, which serves this client.
	ActiveServer pulumi.StringPtrInput
	// The IP address of the DHCP lease to be created.
	Address pulumi.StringPtrInput
	// Address list to which address will be added if lease is bound.
	AddressLists pulumi.StringPtrInput
	// Circuit ID of DHCP relay agent. If each character should be valid ASCII text symbol or else this value is displayed as hex dump.
	AgentCircuitId pulumi.StringPtrInput
	// Remote ID, set by DHCP relay agent.
	AgentRemoteId pulumi.StringPtrInput
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	AllowDualStackQueue pulumi.BoolPtrInput
	// Send all replies as broadcasts.
	AlwaysBroadcast pulumi.BoolPtrInput
	// Whether to block access for this DHCP client (true|false).
	BlockAccess pulumi.BoolPtrInput
	// Whether the lease is blocked.
	Blocked pulumi.BoolPtrInput
	// If specified, must match DHCP 'client identifier' option of the request.
	ClientId pulumi.StringPtrInput
	Comment  pulumi.StringPtrInput
	// Add additional DHCP options.
	DhcpOption pulumi.StringPtrInput
	// Add additional set of DHCP options.
	DhcpOptionSet pulumi.StringPtrInput
	Disabled      pulumi.BoolPtrInput
	// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device. Defaults to false.
	Dynamic pulumi.BoolPtrInput
	// Time until lease expires.
	ExpiresAfter pulumi.StringPtrInput
	// The hostname of the device
	HostName pulumi.StringPtrInput
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	InsertQueueBefore pulumi.StringPtrInput
	LastSeen          pulumi.StringPtrInput
	// Time that the client may use the address. If set to 0s lease will never expire.
	LeaseTime pulumi.StringPtrInput
	// The MAC addreess of the DHCP lease to be created.
	MacAddress pulumi.StringPtrInput
	// Shows if this dynamic lease is authenticated by RADIUS or not.
	Radius pulumi.StringPtrInput
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	RateLimit pulumi.StringPtrInput
	// Server name which serves this client.
	Server pulumi.StringPtrInput
	// Source MAC address.
	SrcMacAddress pulumi.StringPtrInput
	// Lease status.
	Status pulumi.StringPtrInput
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	UseSrcMac pulumi.BoolPtrInput
}

func (ResourceDhcpServerLeaseState) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceDhcpServerLeaseState)(nil)).Elem()
}

type resourceDhcpServerLeaseArgs struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ *int `pulumi:"___id_"`
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ *string `pulumi:"___path_"`
	// The IP address of the DHCP lease to be created.
	Address string `pulumi:"address"`
	// Address list to which address will be added if lease is bound.
	AddressLists *string `pulumi:"addressLists"`
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	AllowDualStackQueue *bool `pulumi:"allowDualStackQueue"`
	// Send all replies as broadcasts.
	AlwaysBroadcast *bool `pulumi:"alwaysBroadcast"`
	// Whether to block access for this DHCP client (true|false).
	BlockAccess *bool `pulumi:"blockAccess"`
	// If specified, must match DHCP 'client identifier' option of the request.
	ClientId *string `pulumi:"clientId"`
	Comment  *string `pulumi:"comment"`
	// Add additional DHCP options.
	DhcpOption *string `pulumi:"dhcpOption"`
	// Add additional set of DHCP options.
	DhcpOptionSet *string `pulumi:"dhcpOptionSet"`
	Disabled      *bool   `pulumi:"disabled"`
	// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device. Defaults to false.
	Dynamic *bool `pulumi:"dynamic"`
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	InsertQueueBefore *string `pulumi:"insertQueueBefore"`
	// Time that the client may use the address. If set to 0s lease will never expire.
	LeaseTime *string `pulumi:"leaseTime"`
	// The MAC addreess of the DHCP lease to be created.
	MacAddress string `pulumi:"macAddress"`
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	RateLimit *string `pulumi:"rateLimit"`
	// Server name which serves this client.
	Server *string `pulumi:"server"`
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	UseSrcMac *bool `pulumi:"useSrcMac"`
}

// The set of arguments for constructing a ResourceDhcpServerLease resource.
type ResourceDhcpServerLeaseArgs struct {
	// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
	___id_ pulumi.IntPtrInput
	// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
	___path_ pulumi.StringPtrInput
	// The IP address of the DHCP lease to be created.
	Address pulumi.StringInput
	// Address list to which address will be added if lease is bound.
	AddressLists pulumi.StringPtrInput
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	AllowDualStackQueue pulumi.BoolPtrInput
	// Send all replies as broadcasts.
	AlwaysBroadcast pulumi.BoolPtrInput
	// Whether to block access for this DHCP client (true|false).
	BlockAccess pulumi.BoolPtrInput
	// If specified, must match DHCP 'client identifier' option of the request.
	ClientId pulumi.StringPtrInput
	Comment  pulumi.StringPtrInput
	// Add additional DHCP options.
	DhcpOption pulumi.StringPtrInput
	// Add additional set of DHCP options.
	DhcpOptionSet pulumi.StringPtrInput
	Disabled      pulumi.BoolPtrInput
	// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device. Defaults to false.
	Dynamic pulumi.BoolPtrInput
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	InsertQueueBefore pulumi.StringPtrInput
	// Time that the client may use the address. If set to 0s lease will never expire.
	LeaseTime pulumi.StringPtrInput
	// The MAC addreess of the DHCP lease to be created.
	MacAddress pulumi.StringInput
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	RateLimit pulumi.StringPtrInput
	// Server name which serves this client.
	Server pulumi.StringPtrInput
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	UseSrcMac pulumi.BoolPtrInput
}

func (ResourceDhcpServerLeaseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceDhcpServerLeaseArgs)(nil)).Elem()
}

type ResourceDhcpServerLeaseInput interface {
	pulumi.Input

	ToResourceDhcpServerLeaseOutput() ResourceDhcpServerLeaseOutput
	ToResourceDhcpServerLeaseOutputWithContext(ctx context.Context) ResourceDhcpServerLeaseOutput
}

func (*ResourceDhcpServerLease) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceDhcpServerLease)(nil)).Elem()
}

func (i *ResourceDhcpServerLease) ToResourceDhcpServerLeaseOutput() ResourceDhcpServerLeaseOutput {
	return i.ToResourceDhcpServerLeaseOutputWithContext(context.Background())
}

func (i *ResourceDhcpServerLease) ToResourceDhcpServerLeaseOutputWithContext(ctx context.Context) ResourceDhcpServerLeaseOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceDhcpServerLeaseOutput)
}

// ResourceDhcpServerLeaseArrayInput is an input type that accepts ResourceDhcpServerLeaseArray and ResourceDhcpServerLeaseArrayOutput values.
// You can construct a concrete instance of `ResourceDhcpServerLeaseArrayInput` via:
//
//	ResourceDhcpServerLeaseArray{ ResourceDhcpServerLeaseArgs{...} }
type ResourceDhcpServerLeaseArrayInput interface {
	pulumi.Input

	ToResourceDhcpServerLeaseArrayOutput() ResourceDhcpServerLeaseArrayOutput
	ToResourceDhcpServerLeaseArrayOutputWithContext(context.Context) ResourceDhcpServerLeaseArrayOutput
}

type ResourceDhcpServerLeaseArray []ResourceDhcpServerLeaseInput

func (ResourceDhcpServerLeaseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ResourceDhcpServerLease)(nil)).Elem()
}

func (i ResourceDhcpServerLeaseArray) ToResourceDhcpServerLeaseArrayOutput() ResourceDhcpServerLeaseArrayOutput {
	return i.ToResourceDhcpServerLeaseArrayOutputWithContext(context.Background())
}

func (i ResourceDhcpServerLeaseArray) ToResourceDhcpServerLeaseArrayOutputWithContext(ctx context.Context) ResourceDhcpServerLeaseArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceDhcpServerLeaseArrayOutput)
}

// ResourceDhcpServerLeaseMapInput is an input type that accepts ResourceDhcpServerLeaseMap and ResourceDhcpServerLeaseMapOutput values.
// You can construct a concrete instance of `ResourceDhcpServerLeaseMapInput` via:
//
//	ResourceDhcpServerLeaseMap{ "key": ResourceDhcpServerLeaseArgs{...} }
type ResourceDhcpServerLeaseMapInput interface {
	pulumi.Input

	ToResourceDhcpServerLeaseMapOutput() ResourceDhcpServerLeaseMapOutput
	ToResourceDhcpServerLeaseMapOutputWithContext(context.Context) ResourceDhcpServerLeaseMapOutput
}

type ResourceDhcpServerLeaseMap map[string]ResourceDhcpServerLeaseInput

func (ResourceDhcpServerLeaseMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ResourceDhcpServerLease)(nil)).Elem()
}

func (i ResourceDhcpServerLeaseMap) ToResourceDhcpServerLeaseMapOutput() ResourceDhcpServerLeaseMapOutput {
	return i.ToResourceDhcpServerLeaseMapOutputWithContext(context.Background())
}

func (i ResourceDhcpServerLeaseMap) ToResourceDhcpServerLeaseMapOutputWithContext(ctx context.Context) ResourceDhcpServerLeaseMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceDhcpServerLeaseMapOutput)
}

type ResourceDhcpServerLeaseOutput struct{ *pulumi.OutputState }

func (ResourceDhcpServerLeaseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceDhcpServerLease)(nil)).Elem()
}

func (o ResourceDhcpServerLeaseOutput) ToResourceDhcpServerLeaseOutput() ResourceDhcpServerLeaseOutput {
	return o
}

func (o ResourceDhcpServerLeaseOutput) ToResourceDhcpServerLeaseOutputWithContext(ctx context.Context) ResourceDhcpServerLeaseOutput {
	return o
}

// <em>Resource ID type (.id / name). This is an internal service field, setting a value is not required.</em>
func (o ResourceDhcpServerLeaseOutput) ___id_() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.IntPtrOutput { return v.___id_ }).(pulumi.IntPtrOutput)
}

// <em>Resource path for CRUD operations. This is an internal service field, setting a value is not required.</em>
func (o ResourceDhcpServerLeaseOutput) ___path_() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringPtrOutput { return v.___path_ }).(pulumi.StringPtrOutput)
}

// The IP address of the machine currently holding the DHCP lease.
func (o ResourceDhcpServerLeaseOutput) ActiveAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.ActiveAddress }).(pulumi.StringOutput)
}

// Actual client-id of the client.
func (o ResourceDhcpServerLeaseOutput) ActiveClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.ActiveClientId }).(pulumi.StringOutput)
}

// The hostname of the machine currently holding the DHCP lease.
func (o ResourceDhcpServerLeaseOutput) ActiveHostname() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.ActiveHostname }).(pulumi.StringOutput)
}

// The MAC address of of the machine currently holding the DHCP lease.
func (o ResourceDhcpServerLeaseOutput) ActiveMacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.ActiveMacAddress }).(pulumi.StringOutput)
}

// Actual dhcp server, which serves this client.
func (o ResourceDhcpServerLeaseOutput) ActiveServer() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.ActiveServer }).(pulumi.StringOutput)
}

// The IP address of the DHCP lease to be created.
func (o ResourceDhcpServerLeaseOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.Address }).(pulumi.StringOutput)
}

// Address list to which address will be added if lease is bound.
func (o ResourceDhcpServerLeaseOutput) AddressLists() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringPtrOutput { return v.AddressLists }).(pulumi.StringPtrOutput)
}

// Circuit ID of DHCP relay agent. If each character should be valid ASCII text symbol or else this value is displayed as hex dump.
func (o ResourceDhcpServerLeaseOutput) AgentCircuitId() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.AgentCircuitId }).(pulumi.StringOutput)
}

// Remote ID, set by DHCP relay agent.
func (o ResourceDhcpServerLeaseOutput) AgentRemoteId() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.AgentRemoteId }).(pulumi.StringOutput)
}

// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
func (o ResourceDhcpServerLeaseOutput) AllowDualStackQueue() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.BoolPtrOutput { return v.AllowDualStackQueue }).(pulumi.BoolPtrOutput)
}

// Send all replies as broadcasts.
func (o ResourceDhcpServerLeaseOutput) AlwaysBroadcast() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.BoolPtrOutput { return v.AlwaysBroadcast }).(pulumi.BoolPtrOutput)
}

// Whether to block access for this DHCP client (true|false).
func (o ResourceDhcpServerLeaseOutput) BlockAccess() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.BoolPtrOutput { return v.BlockAccess }).(pulumi.BoolPtrOutput)
}

// Whether the lease is blocked.
func (o ResourceDhcpServerLeaseOutput) Blocked() pulumi.BoolOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.BoolOutput { return v.Blocked }).(pulumi.BoolOutput)
}

// If specified, must match DHCP 'client identifier' option of the request.
func (o ResourceDhcpServerLeaseOutput) ClientId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringPtrOutput { return v.ClientId }).(pulumi.StringPtrOutput)
}

func (o ResourceDhcpServerLeaseOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// Add additional DHCP options.
func (o ResourceDhcpServerLeaseOutput) DhcpOption() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringPtrOutput { return v.DhcpOption }).(pulumi.StringPtrOutput)
}

// Add additional set of DHCP options.
func (o ResourceDhcpServerLeaseOutput) DhcpOptionSet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringPtrOutput { return v.DhcpOptionSet }).(pulumi.StringPtrOutput)
}

func (o ResourceDhcpServerLeaseOutput) Disabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.BoolPtrOutput { return v.Disabled }).(pulumi.BoolPtrOutput)
}

// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device. Defaults to false.
func (o ResourceDhcpServerLeaseOutput) Dynamic() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.BoolPtrOutput { return v.Dynamic }).(pulumi.BoolPtrOutput)
}

// Time until lease expires.
func (o ResourceDhcpServerLeaseOutput) ExpiresAfter() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.ExpiresAfter }).(pulumi.StringOutput)
}

// The hostname of the device
func (o ResourceDhcpServerLeaseOutput) HostName() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.HostName }).(pulumi.StringOutput)
}

// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
func (o ResourceDhcpServerLeaseOutput) InsertQueueBefore() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringPtrOutput { return v.InsertQueueBefore }).(pulumi.StringPtrOutput)
}

func (o ResourceDhcpServerLeaseOutput) LastSeen() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.LastSeen }).(pulumi.StringOutput)
}

// Time that the client may use the address. If set to 0s lease will never expire.
func (o ResourceDhcpServerLeaseOutput) LeaseTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringPtrOutput { return v.LeaseTime }).(pulumi.StringPtrOutput)
}

// The MAC addreess of the DHCP lease to be created.
func (o ResourceDhcpServerLeaseOutput) MacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.MacAddress }).(pulumi.StringOutput)
}

// Shows if this dynamic lease is authenticated by RADIUS or not.
func (o ResourceDhcpServerLeaseOutput) Radius() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.Radius }).(pulumi.StringOutput)
}

// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
func (o ResourceDhcpServerLeaseOutput) RateLimit() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringPtrOutput { return v.RateLimit }).(pulumi.StringPtrOutput)
}

// Server name which serves this client.
func (o ResourceDhcpServerLeaseOutput) Server() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringPtrOutput { return v.Server }).(pulumi.StringPtrOutput)
}

// Source MAC address.
func (o ResourceDhcpServerLeaseOutput) SrcMacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.SrcMacAddress }).(pulumi.StringOutput)
}

// Lease status.
func (o ResourceDhcpServerLeaseOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// When this option is set server uses source MAC address instead of received CHADDR to assign address.
func (o ResourceDhcpServerLeaseOutput) UseSrcMac() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ResourceDhcpServerLease) pulumi.BoolPtrOutput { return v.UseSrcMac }).(pulumi.BoolPtrOutput)
}

type ResourceDhcpServerLeaseArrayOutput struct{ *pulumi.OutputState }

func (ResourceDhcpServerLeaseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ResourceDhcpServerLease)(nil)).Elem()
}

func (o ResourceDhcpServerLeaseArrayOutput) ToResourceDhcpServerLeaseArrayOutput() ResourceDhcpServerLeaseArrayOutput {
	return o
}

func (o ResourceDhcpServerLeaseArrayOutput) ToResourceDhcpServerLeaseArrayOutputWithContext(ctx context.Context) ResourceDhcpServerLeaseArrayOutput {
	return o
}

func (o ResourceDhcpServerLeaseArrayOutput) Index(i pulumi.IntInput) ResourceDhcpServerLeaseOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ResourceDhcpServerLease {
		return vs[0].([]*ResourceDhcpServerLease)[vs[1].(int)]
	}).(ResourceDhcpServerLeaseOutput)
}

type ResourceDhcpServerLeaseMapOutput struct{ *pulumi.OutputState }

func (ResourceDhcpServerLeaseMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ResourceDhcpServerLease)(nil)).Elem()
}

func (o ResourceDhcpServerLeaseMapOutput) ToResourceDhcpServerLeaseMapOutput() ResourceDhcpServerLeaseMapOutput {
	return o
}

func (o ResourceDhcpServerLeaseMapOutput) ToResourceDhcpServerLeaseMapOutputWithContext(ctx context.Context) ResourceDhcpServerLeaseMapOutput {
	return o
}

func (o ResourceDhcpServerLeaseMapOutput) MapIndex(k pulumi.StringInput) ResourceDhcpServerLeaseOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ResourceDhcpServerLease {
		return vs[0].(map[string]*ResourceDhcpServerLease)[vs[1].(string)]
	}).(ResourceDhcpServerLeaseOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceDhcpServerLeaseInput)(nil)).Elem(), &ResourceDhcpServerLease{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceDhcpServerLeaseArrayInput)(nil)).Elem(), ResourceDhcpServerLeaseArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceDhcpServerLeaseMapInput)(nil)).Elem(), ResourceDhcpServerLeaseMap{})
	pulumi.RegisterOutputType(ResourceDhcpServerLeaseOutput{})
	pulumi.RegisterOutputType(ResourceDhcpServerLeaseArrayOutput{})
	pulumi.RegisterOutputType(ResourceDhcpServerLeaseMapOutput{})
}
